/* Indicator.c generated by valac 0.34.4, the Vala compiler
 * generated from Indicator.vala, do not modify */

/*
 * Copyright (c) 2011-2015 Wingpanel Developers (http://launchpad.net/wingpanel)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define WINGPANEL_TYPE_INDICATOR (wingpanel_indicator_get_type ())
#define WINGPANEL_INDICATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_TYPE_INDICATOR, WingpanelIndicator))
#define WINGPANEL_INDICATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_TYPE_INDICATOR, WingpanelIndicatorClass))
#define WINGPANEL_IS_INDICATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_TYPE_INDICATOR))
#define WINGPANEL_IS_INDICATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_TYPE_INDICATOR))
#define WINGPANEL_INDICATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_TYPE_INDICATOR, WingpanelIndicatorClass))

typedef struct _WingpanelIndicator WingpanelIndicator;
typedef struct _WingpanelIndicatorClass WingpanelIndicatorClass;
typedef struct _WingpanelIndicatorPrivate WingpanelIndicatorPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _WingpanelIndicator {
	GObject parent_instance;
	WingpanelIndicatorPrivate * priv;
};

struct _WingpanelIndicatorClass {
	GObjectClass parent_class;
	GtkWidget* (*get_display_widget) (WingpanelIndicator* self);
	GtkWidget* (*get_widget) (WingpanelIndicator* self);
	void (*opened) (WingpanelIndicator* self);
	void (*closed) (WingpanelIndicator* self);
};

struct _WingpanelIndicatorPrivate {
	gchar* _code_name;
	gchar* _display_name;
	gchar* _description;
	gboolean _visible;
};


static gpointer wingpanel_indicator_parent_class = NULL;

GType wingpanel_indicator_get_type (void) G_GNUC_CONST;
#define WINGPANEL_INDICATOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), WINGPANEL_TYPE_INDICATOR, WingpanelIndicatorPrivate))
enum  {
	WINGPANEL_INDICATOR_DUMMY_PROPERTY,
	WINGPANEL_INDICATOR_CODE_NAME,
	WINGPANEL_INDICATOR_DISPLAY_NAME,
	WINGPANEL_INDICATOR_DESCRIPTION,
	WINGPANEL_INDICATOR_VISIBLE
};
#define WINGPANEL_INDICATOR_APP_LAUNCHER "app-launcher"
#define WINGPANEL_INDICATOR_SESSION "session"
#define WINGPANEL_INDICATOR_DATETIME "datetime"
#define WINGPANEL_INDICATOR_NETWORK "network"
#define WINGPANEL_INDICATOR_MESSAGES "messages"
#define WINGPANEL_INDICATOR_SOUND "sound"
#define WINGPANEL_INDICATOR_POWER "power"
#define WINGPANEL_INDICATOR_SYNC "sync"
#define WINGPANEL_INDICATOR_PRINTER "printer"
#define WINGPANEL_INDICATOR_BLUETOOTH "bluetooth"
#define WINGPANEL_INDICATOR_KEYBOARD "keyboard"
GtkWidget* wingpanel_indicator_get_display_widget (WingpanelIndicator* self);
static GtkWidget* wingpanel_indicator_real_get_display_widget (WingpanelIndicator* self);
GtkWidget* wingpanel_indicator_get_widget (WingpanelIndicator* self);
static GtkWidget* wingpanel_indicator_real_get_widget (WingpanelIndicator* self);
void wingpanel_indicator_opened (WingpanelIndicator* self);
static void wingpanel_indicator_real_opened (WingpanelIndicator* self);
void wingpanel_indicator_closed (WingpanelIndicator* self);
static void wingpanel_indicator_real_closed (WingpanelIndicator* self);
WingpanelIndicator* wingpanel_indicator_construct (GType object_type);
const gchar* wingpanel_indicator_get_code_name (WingpanelIndicator* self);
static void wingpanel_indicator_set_code_name (WingpanelIndicator* self, const gchar* value);
const gchar* wingpanel_indicator_get_display_name (WingpanelIndicator* self);
static void wingpanel_indicator_set_display_name (WingpanelIndicator* self, const gchar* value);
const gchar* wingpanel_indicator_get_description (WingpanelIndicator* self);
static void wingpanel_indicator_set_description (WingpanelIndicator* self, const gchar* value);
gboolean wingpanel_indicator_get_visible (WingpanelIndicator* self);
void wingpanel_indicator_set_visible (WingpanelIndicator* self, gboolean value);
static void wingpanel_indicator_finalize (GObject* obj);
static void _vala_wingpanel_indicator_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_wingpanel_indicator_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
     * Returns the display widget that will be displayed in the panel.
     * Middle click and scroll events will be passed to this widget.
     * If get_widget () returns null all EventButton events will be passed.
     *
     * @return a {@link Gtk.Widget} that represents the status.
     */
static GtkWidget* wingpanel_indicator_real_get_display_widget (WingpanelIndicator* self) {
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_critical ("Type `%s' does not implement abstract method `wingpanel_indicator_get_display_widget'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return NULL;
#line 120 "Indicator.c"
}


GtkWidget* wingpanel_indicator_get_display_widget (WingpanelIndicator* self) {
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return WINGPANEL_INDICATOR_GET_CLASS (self)->get_display_widget (self);
#line 129 "Indicator.c"
}


/**
     * Returns the widget that will be displayed in the popover.
     * Return null if no popover should be shown.
     *
     * @return a {@link Gtk.Widget} containing the popover interface.
     */
static GtkWidget* wingpanel_indicator_real_get_widget (WingpanelIndicator* self) {
#line 69 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_critical ("Type `%s' does not implement abstract method `wingpanel_indicator_get_widget'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 69 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return NULL;
#line 144 "Indicator.c"
}


GtkWidget* wingpanel_indicator_get_widget (WingpanelIndicator* self) {
#line 69 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 69 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return WINGPANEL_INDICATOR_GET_CLASS (self)->get_widget (self);
#line 153 "Indicator.c"
}


/**
     * Called when the indicator popover opened.
     */
static void wingpanel_indicator_real_opened (WingpanelIndicator* self) {
#line 74 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_critical ("Type `%s' does not implement abstract method `wingpanel_indicator_opened'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 74 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return;
#line 165 "Indicator.c"
}


void wingpanel_indicator_opened (WingpanelIndicator* self) {
#line 74 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_if_fail (self != NULL);
#line 74 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	WINGPANEL_INDICATOR_GET_CLASS (self)->opened (self);
#line 174 "Indicator.c"
}


/**
     * Called when the indicator popover closed.
     */
static void wingpanel_indicator_real_closed (WingpanelIndicator* self) {
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_critical ("Type `%s' does not implement abstract method `wingpanel_indicator_closed'", g_type_name (G_TYPE_FROM_INSTANCE (self)));
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return;
#line 186 "Indicator.c"
}


void wingpanel_indicator_closed (WingpanelIndicator* self) {
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_if_fail (self != NULL);
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	WINGPANEL_INDICATOR_GET_CLASS (self)->closed (self);
#line 195 "Indicator.c"
}


WingpanelIndicator* wingpanel_indicator_construct (GType object_type) {
	WingpanelIndicator * self = NULL;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	self = (WingpanelIndicator*) g_object_new (object_type, NULL);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return self;
#line 205 "Indicator.c"
}


const gchar* wingpanel_indicator_get_code_name (WingpanelIndicator* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp0_ = self->priv->_code_name;
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	result = _tmp0_;
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return result;
#line 220 "Indicator.c"
}


static void wingpanel_indicator_set_code_name (WingpanelIndicator* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_if_fail (self != NULL);
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp0_ = value;
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_g_free0 (self->priv->_code_name);
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	self->priv->_code_name = _tmp1_;
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_object_notify ((GObject *) self, "code-name");
#line 239 "Indicator.c"
}


const gchar* wingpanel_indicator_get_display_name (WingpanelIndicator* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp0_ = self->priv->_display_name;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	result = _tmp0_;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return result;
#line 254 "Indicator.c"
}


static void wingpanel_indicator_set_display_name (WingpanelIndicator* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_if_fail (self != NULL);
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp0_ = value;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_g_free0 (self->priv->_display_name);
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	self->priv->_display_name = _tmp1_;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_object_notify ((GObject *) self, "display-name");
#line 273 "Indicator.c"
}


const gchar* wingpanel_indicator_get_description (WingpanelIndicator* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp0_ = self->priv->_description;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	result = _tmp0_;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return result;
#line 288 "Indicator.c"
}


static void wingpanel_indicator_set_description (WingpanelIndicator* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_if_fail (self != NULL);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp0_ = value;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_g_free0 (self->priv->_description);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	self->priv->_description = _tmp1_;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_object_notify ((GObject *) self, "description");
#line 307 "Indicator.c"
}


gboolean wingpanel_indicator_get_visible (WingpanelIndicator* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp0_ = self->priv->_visible;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	result = _tmp0_;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	return result;
#line 322 "Indicator.c"
}


void wingpanel_indicator_set_visible (WingpanelIndicator* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_return_if_fail (self != NULL);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_tmp0_ = value;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	self->priv->_visible = _tmp0_;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_object_notify ((GObject *) self, "visible");
#line 336 "Indicator.c"
}


static void wingpanel_indicator_class_init (WingpanelIndicatorClass * klass) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	wingpanel_indicator_parent_class = g_type_class_peek_parent (klass);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_type_class_add_private (klass, sizeof (WingpanelIndicatorPrivate));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	((WingpanelIndicatorClass *) klass)->get_display_widget = wingpanel_indicator_real_get_display_widget;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	((WingpanelIndicatorClass *) klass)->get_widget = wingpanel_indicator_real_get_widget;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	((WingpanelIndicatorClass *) klass)->opened = wingpanel_indicator_real_opened;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	((WingpanelIndicatorClass *) klass)->closed = wingpanel_indicator_real_closed;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_wingpanel_indicator_get_property;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_wingpanel_indicator_set_property;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	G_OBJECT_CLASS (klass)->finalize = wingpanel_indicator_finalize;
#line 359 "Indicator.c"
	/**
	     * The unique name representing the indicator.
	     * It is also used for the indicator ordering.
	     */
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), WINGPANEL_INDICATOR_CODE_NAME, g_param_spec_string ("code-name", "code-name", "code-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 366 "Indicator.c"
	/**
	     * The localised name of the indicator.
	     */
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), WINGPANEL_INDICATOR_DISPLAY_NAME, g_param_spec_string ("display-name", "display-name", "display-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 372 "Indicator.c"
	/**
	     * A short description of the indicator.
	     */
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), WINGPANEL_INDICATOR_DESCRIPTION, g_param_spec_string ("description", "description", "description", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 378 "Indicator.c"
	/**
	     * Defines if the indicator display widget should be shown or not.
	     */
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), WINGPANEL_INDICATOR_VISIBLE, g_param_spec_boolean ("visible", "visible", "visible", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 384 "Indicator.c"
	/**
	     * Request a popover closing.
	     */
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	g_signal_new ("close", WINGPANEL_TYPE_INDICATOR, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 390 "Indicator.c"
}


static void wingpanel_indicator_instance_init (WingpanelIndicator * self) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	self->priv = WINGPANEL_INDICATOR_GET_PRIVATE (self);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	self->priv->_visible = FALSE;
#line 399 "Indicator.c"
}


static void wingpanel_indicator_finalize (GObject* obj) {
	WingpanelIndicator * self;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WINGPANEL_TYPE_INDICATOR, WingpanelIndicator);
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_g_free0 (self->priv->_code_name);
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_g_free0 (self->priv->_display_name);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	_g_free0 (self->priv->_description);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	G_OBJECT_CLASS (wingpanel_indicator_parent_class)->finalize (obj);
#line 415 "Indicator.c"
}


GType wingpanel_indicator_get_type (void) {
	static volatile gsize wingpanel_indicator_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_indicator_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelIndicatorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_indicator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelIndicator), 0, (GInstanceInitFunc) wingpanel_indicator_instance_init, NULL };
		GType wingpanel_indicator_type_id;
		wingpanel_indicator_type_id = g_type_register_static (G_TYPE_OBJECT, "WingpanelIndicator", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&wingpanel_indicator_type_id__volatile, wingpanel_indicator_type_id);
	}
	return wingpanel_indicator_type_id__volatile;
}


static void _vala_wingpanel_indicator_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	WingpanelIndicator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, WINGPANEL_TYPE_INDICATOR, WingpanelIndicator);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	switch (property_id) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		case WINGPANEL_INDICATOR_CODE_NAME:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		g_value_set_string (value, wingpanel_indicator_get_code_name (self));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		case WINGPANEL_INDICATOR_DISPLAY_NAME:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		g_value_set_string (value, wingpanel_indicator_get_display_name (self));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		case WINGPANEL_INDICATOR_DESCRIPTION:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		g_value_set_string (value, wingpanel_indicator_get_description (self));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		case WINGPANEL_INDICATOR_VISIBLE:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		g_value_set_boolean (value, wingpanel_indicator_get_visible (self));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 460 "Indicator.c"
		default:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 466 "Indicator.c"
	}
}


static void _vala_wingpanel_indicator_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	WingpanelIndicator * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, WINGPANEL_TYPE_INDICATOR, WingpanelIndicator);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
	switch (property_id) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		case WINGPANEL_INDICATOR_CODE_NAME:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		wingpanel_indicator_set_code_name (self, g_value_get_string (value));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		case WINGPANEL_INDICATOR_DISPLAY_NAME:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		wingpanel_indicator_set_display_name (self, g_value_get_string (value));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		case WINGPANEL_INDICATOR_DESCRIPTION:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		wingpanel_indicator_set_description (self, g_value_get_string (value));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		case WINGPANEL_INDICATOR_VISIBLE:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		wingpanel_indicator_set_visible (self, g_value_get_boolean (value));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 500 "Indicator.c"
		default:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Indicator.vala"
		break;
#line 506 "Indicator.c"
	}
}



