/* DBusServer.c generated by valac 0.34.4, the Vala compiler
 * generated from DBusServer.vala, do not modify */

/*
 * Copyright (c) 2011-2015 Wingpanel Developers (http://launchpad.net/wingpanel)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <string.h>


#define WINGPANEL_INTERFACE_TYPE_DBUS_SERVER (wingpanel_interface_dbus_server_get_type ())
#define WINGPANEL_INTERFACE_DBUS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_INTERFACE_TYPE_DBUS_SERVER, WingpanelInterfaceDBusServer))
#define WINGPANEL_INTERFACE_DBUS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_INTERFACE_TYPE_DBUS_SERVER, WingpanelInterfaceDBusServerClass))
#define WINGPANEL_INTERFACE_IS_DBUS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_INTERFACE_TYPE_DBUS_SERVER))
#define WINGPANEL_INTERFACE_IS_DBUS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_INTERFACE_TYPE_DBUS_SERVER))
#define WINGPANEL_INTERFACE_DBUS_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_INTERFACE_TYPE_DBUS_SERVER, WingpanelInterfaceDBusServerClass))

typedef struct _WingpanelInterfaceDBusServer WingpanelInterfaceDBusServer;
typedef struct _WingpanelInterfaceDBusServerClass WingpanelInterfaceDBusServerClass;
typedef struct _WingpanelInterfaceDBusServerPrivate WingpanelInterfaceDBusServerPrivate;

#define WINGPANEL_INTERFACE_TYPE_BACKGROUND_MANAGER (wingpanel_interface_background_manager_get_type ())
#define WINGPANEL_INTERFACE_BACKGROUND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_INTERFACE_TYPE_BACKGROUND_MANAGER, WingpanelInterfaceBackgroundManager))
#define WINGPANEL_INTERFACE_BACKGROUND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_INTERFACE_TYPE_BACKGROUND_MANAGER, WingpanelInterfaceBackgroundManagerClass))
#define WINGPANEL_INTERFACE_IS_BACKGROUND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_INTERFACE_TYPE_BACKGROUND_MANAGER))
#define WINGPANEL_INTERFACE_IS_BACKGROUND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_INTERFACE_TYPE_BACKGROUND_MANAGER))
#define WINGPANEL_INTERFACE_BACKGROUND_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_INTERFACE_TYPE_BACKGROUND_MANAGER, WingpanelInterfaceBackgroundManagerClass))

typedef struct _WingpanelInterfaceBackgroundManager WingpanelInterfaceBackgroundManager;
typedef struct _WingpanelInterfaceBackgroundManagerClass WingpanelInterfaceBackgroundManagerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_BACKGROUND_STATE (background_state_get_type ())

#define WINGPANEL_INTERFACE_TYPE_FOCUS_MANAGER (wingpanel_interface_focus_manager_get_type ())
#define WINGPANEL_INTERFACE_FOCUS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_INTERFACE_TYPE_FOCUS_MANAGER, WingpanelInterfaceFocusManager))
#define WINGPANEL_INTERFACE_FOCUS_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_INTERFACE_TYPE_FOCUS_MANAGER, WingpanelInterfaceFocusManagerClass))
#define WINGPANEL_INTERFACE_IS_FOCUS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_INTERFACE_TYPE_FOCUS_MANAGER))
#define WINGPANEL_INTERFACE_IS_FOCUS_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_INTERFACE_TYPE_FOCUS_MANAGER))
#define WINGPANEL_INTERFACE_FOCUS_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_INTERFACE_TYPE_FOCUS_MANAGER, WingpanelInterfaceFocusManagerClass))

typedef struct _WingpanelInterfaceFocusManager WingpanelInterfaceFocusManager;
typedef struct _WingpanelInterfaceFocusManagerClass WingpanelInterfaceFocusManagerClass;

struct _WingpanelInterfaceDBusServer {
	GObject parent_instance;
	WingpanelInterfaceDBusServerPrivate * priv;
};

struct _WingpanelInterfaceDBusServerClass {
	GObjectClass parent_class;
};

struct _WingpanelInterfaceDBusServerPrivate {
	WingpanelInterfaceBackgroundManager* background_manager;
};

typedef enum  {
	BACKGROUND_STATE_LIGHT,
	BACKGROUND_STATE_DARK,
	BACKGROUND_STATE_MAXIMIZED,
	BACKGROUND_STATE_TRANSLUCENT
} BackgroundState;


static gpointer wingpanel_interface_dbus_server_parent_class = NULL;

GType wingpanel_interface_dbus_server_get_type (void) G_GNUC_CONST;
guint wingpanel_interface_dbus_server_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType wingpanel_interface_background_manager_get_type (void) G_GNUC_CONST;
#define WINGPANEL_INTERFACE_DBUS_SERVER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), WINGPANEL_INTERFACE_TYPE_DBUS_SERVER, WingpanelInterfaceDBusServerPrivate))
enum  {
	WINGPANEL_INTERFACE_DBUS_SERVER_DUMMY_PROPERTY
};
void wingpanel_interface_dbus_server_initialize (WingpanelInterfaceDBusServer* self, gint monitor, gint panel_height);
WingpanelInterfaceBackgroundManager* wingpanel_interface_background_manager_new (gint monitor, gint panel_height);
WingpanelInterfaceBackgroundManager* wingpanel_interface_background_manager_construct (GType object_type, gint monitor, gint panel_height);
GType background_state_get_type (void) G_GNUC_CONST;
static void __lambda12_ (WingpanelInterfaceDBusServer* self, BackgroundState state, guint animation_duration);
static void ___lambda12__wingpanel_interface_background_manager_state_changed (WingpanelInterfaceBackgroundManager* _sender, BackgroundState state, guint animation_duration, gpointer self);
void wingpanel_interface_dbus_server_remember_focused_window (WingpanelInterfaceDBusServer* self);
GType wingpanel_interface_focus_manager_get_type (void) G_GNUC_CONST;
WingpanelInterfaceFocusManager* wingpanel_interface_focus_manager_get_default (void);
void wingpanel_interface_focus_manager_remember_focused_window (WingpanelInterfaceFocusManager* self);
void wingpanel_interface_dbus_server_restore_focused_window (WingpanelInterfaceDBusServer* self);
void wingpanel_interface_focus_manager_restore_focused_window (WingpanelInterfaceFocusManager* self);
WingpanelInterfaceDBusServer* wingpanel_interface_dbus_server_new (void);
WingpanelInterfaceDBusServer* wingpanel_interface_dbus_server_construct (GType object_type);
static void g_cclosure_user_marshal_VOID__ENUM_UINT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void wingpanel_interface_dbus_server_finalize (GObject* obj);
static void _dbus_wingpanel_interface_dbus_server_initialize (WingpanelInterfaceDBusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void _dbus_wingpanel_interface_dbus_server_remember_focused_window (WingpanelInterfaceDBusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void _dbus_wingpanel_interface_dbus_server_restore_focused_window (WingpanelInterfaceDBusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void wingpanel_interface_dbus_server_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* wingpanel_interface_dbus_server_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean wingpanel_interface_dbus_server_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _dbus_wingpanel_interface_dbus_server_state_changed (GObject* _sender, BackgroundState state, guint animation_duration, gpointer* _data);
static void _wingpanel_interface_dbus_server_unregister_object (gpointer user_data);

static const GDBusArgInfo _wingpanel_interface_dbus_server_dbus_arg_info_initialize_monitor = {-1, "monitor", "i"};
static const GDBusArgInfo _wingpanel_interface_dbus_server_dbus_arg_info_initialize_panel_height = {-1, "panel_height", "i"};
static const GDBusArgInfo * const _wingpanel_interface_dbus_server_dbus_arg_info_initialize_in[] = {&_wingpanel_interface_dbus_server_dbus_arg_info_initialize_monitor, &_wingpanel_interface_dbus_server_dbus_arg_info_initialize_panel_height, NULL};
static const GDBusArgInfo * const _wingpanel_interface_dbus_server_dbus_arg_info_initialize_out[] = {NULL};
static const GDBusMethodInfo _wingpanel_interface_dbus_server_dbus_method_info_initialize = {-1, "Initialize", (GDBusArgInfo **) (&_wingpanel_interface_dbus_server_dbus_arg_info_initialize_in), (GDBusArgInfo **) (&_wingpanel_interface_dbus_server_dbus_arg_info_initialize_out)};
static const GDBusArgInfo * const _wingpanel_interface_dbus_server_dbus_arg_info_remember_focused_window_in[] = {NULL};
static const GDBusArgInfo * const _wingpanel_interface_dbus_server_dbus_arg_info_remember_focused_window_out[] = {NULL};
static const GDBusMethodInfo _wingpanel_interface_dbus_server_dbus_method_info_remember_focused_window = {-1, "RememberFocusedWindow", (GDBusArgInfo **) (&_wingpanel_interface_dbus_server_dbus_arg_info_remember_focused_window_in), (GDBusArgInfo **) (&_wingpanel_interface_dbus_server_dbus_arg_info_remember_focused_window_out)};
static const GDBusArgInfo * const _wingpanel_interface_dbus_server_dbus_arg_info_restore_focused_window_in[] = {NULL};
static const GDBusArgInfo * const _wingpanel_interface_dbus_server_dbus_arg_info_restore_focused_window_out[] = {NULL};
static const GDBusMethodInfo _wingpanel_interface_dbus_server_dbus_method_info_restore_focused_window = {-1, "RestoreFocusedWindow", (GDBusArgInfo **) (&_wingpanel_interface_dbus_server_dbus_arg_info_restore_focused_window_in), (GDBusArgInfo **) (&_wingpanel_interface_dbus_server_dbus_arg_info_restore_focused_window_out)};
static const GDBusMethodInfo * const _wingpanel_interface_dbus_server_dbus_method_info[] = {&_wingpanel_interface_dbus_server_dbus_method_info_initialize, &_wingpanel_interface_dbus_server_dbus_method_info_remember_focused_window, &_wingpanel_interface_dbus_server_dbus_method_info_restore_focused_window, NULL};
static const GDBusArgInfo _wingpanel_interface_dbus_server_dbus_arg_info_state_changed_state = {-1, "state", "i"};
static const GDBusArgInfo _wingpanel_interface_dbus_server_dbus_arg_info_state_changed_animation_duration = {-1, "animation_duration", "u"};
static const GDBusArgInfo * const _wingpanel_interface_dbus_server_dbus_arg_info_state_changed[] = {&_wingpanel_interface_dbus_server_dbus_arg_info_state_changed_state, &_wingpanel_interface_dbus_server_dbus_arg_info_state_changed_animation_duration, NULL};
static const GDBusSignalInfo _wingpanel_interface_dbus_server_dbus_signal_info_state_changed = {-1, "StateChanged", (GDBusArgInfo **) (&_wingpanel_interface_dbus_server_dbus_arg_info_state_changed)};
static const GDBusSignalInfo * const _wingpanel_interface_dbus_server_dbus_signal_info[] = {&_wingpanel_interface_dbus_server_dbus_signal_info_state_changed, NULL};
static const GDBusPropertyInfo * const _wingpanel_interface_dbus_server_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _wingpanel_interface_dbus_server_dbus_interface_info = {-1, "org.pantheon.gala.WingpanelInterface", (GDBusMethodInfo **) (&_wingpanel_interface_dbus_server_dbus_method_info), (GDBusSignalInfo **) (&_wingpanel_interface_dbus_server_dbus_signal_info), (GDBusPropertyInfo **) (&_wingpanel_interface_dbus_server_dbus_property_info)};
static const GDBusInterfaceVTable _wingpanel_interface_dbus_server_dbus_interface_vtable = {wingpanel_interface_dbus_server_dbus_interface_method_call, wingpanel_interface_dbus_server_dbus_interface_get_property, wingpanel_interface_dbus_server_dbus_interface_set_property};

static void __lambda12_ (WingpanelInterfaceDBusServer* self, BackgroundState state, guint animation_duration) {
	BackgroundState _tmp0_ = 0;
	guint _tmp1_ = 0U;
#line 29 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp0_ = state;
#line 29 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp1_ = animation_duration;
#line 29 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	g_signal_emit_by_name (self, "state-changed", _tmp0_, _tmp1_);
#line 149 "DBusServer.c"
}


static void ___lambda12__wingpanel_interface_background_manager_state_changed (WingpanelInterfaceBackgroundManager* _sender, BackgroundState state, guint animation_duration, gpointer self) {
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	__lambda12_ ((WingpanelInterfaceDBusServer*) self, state, animation_duration);
#line 156 "DBusServer.c"
}


void wingpanel_interface_dbus_server_initialize (WingpanelInterfaceDBusServer* self, gint monitor, gint panel_height) {
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	WingpanelInterfaceBackgroundManager* _tmp2_ = NULL;
	WingpanelInterfaceBackgroundManager* _tmp3_ = NULL;
#line 26 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	g_return_if_fail (self != NULL);
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp0_ = monitor;
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp1_ = panel_height;
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp2_ = wingpanel_interface_background_manager_new (_tmp0_, _tmp1_);
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_g_object_unref0 (self->priv->background_manager);
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	self->priv->background_manager = _tmp2_;
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp3_ = self->priv->background_manager;
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	g_signal_connect_object (_tmp3_, "state-changed", (GCallback) ___lambda12__wingpanel_interface_background_manager_state_changed, self, 0);
#line 181 "DBusServer.c"
}


void wingpanel_interface_dbus_server_remember_focused_window (WingpanelInterfaceDBusServer* self) {
	WingpanelInterfaceFocusManager* _tmp0_ = NULL;
	WingpanelInterfaceFocusManager* _tmp1_ = NULL;
#line 33 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	g_return_if_fail (self != NULL);
#line 34 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp0_ = wingpanel_interface_focus_manager_get_default ();
#line 34 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp1_ = _tmp0_;
#line 34 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	wingpanel_interface_focus_manager_remember_focused_window (_tmp1_);
#line 34 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_g_object_unref0 (_tmp1_);
#line 198 "DBusServer.c"
}


void wingpanel_interface_dbus_server_restore_focused_window (WingpanelInterfaceDBusServer* self) {
	WingpanelInterfaceFocusManager* _tmp0_ = NULL;
	WingpanelInterfaceFocusManager* _tmp1_ = NULL;
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	g_return_if_fail (self != NULL);
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp0_ = wingpanel_interface_focus_manager_get_default ();
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_tmp1_ = _tmp0_;
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	wingpanel_interface_focus_manager_restore_focused_window (_tmp1_);
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_g_object_unref0 (_tmp1_);
#line 215 "DBusServer.c"
}


WingpanelInterfaceDBusServer* wingpanel_interface_dbus_server_construct (GType object_type) {
	WingpanelInterfaceDBusServer * self = NULL;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	self = (WingpanelInterfaceDBusServer*) g_object_new (object_type, NULL);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	return self;
#line 225 "DBusServer.c"
}


WingpanelInterfaceDBusServer* wingpanel_interface_dbus_server_new (void) {
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	return wingpanel_interface_dbus_server_construct (WINGPANEL_INTERFACE_TYPE_DBUS_SERVER);
#line 232 "DBusServer.c"
}


static void g_cclosure_user_marshal_VOID__ENUM_UINT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__ENUM_UINT) (gpointer data1, gint arg_1, guint arg_2, gpointer data2);
	register GMarshalFunc_VOID__ENUM_UINT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	g_return_if_fail (n_param_values == 3);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
		data1 = closure->data;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
		data2 = param_values->data[0].v_pointer;
#line 251 "DBusServer.c"
	} else {
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
		data1 = param_values->data[0].v_pointer;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
		data2 = closure->data;
#line 257 "DBusServer.c"
	}
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	callback = (GMarshalFunc_VOID__ENUM_UINT) (marshal_data ? marshal_data : cc->callback);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	callback (data1, g_value_get_enum (param_values + 1), g_value_get_uint (param_values + 2), data2);
#line 263 "DBusServer.c"
}


static void wingpanel_interface_dbus_server_class_init (WingpanelInterfaceDBusServerClass * klass) {
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	wingpanel_interface_dbus_server_parent_class = g_type_class_peek_parent (klass);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	g_type_class_add_private (klass, sizeof (WingpanelInterfaceDBusServerPrivate));
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	G_OBJECT_CLASS (klass)->finalize = wingpanel_interface_dbus_server_finalize;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	g_signal_new ("state_changed", WINGPANEL_INTERFACE_TYPE_DBUS_SERVER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__ENUM_UINT, G_TYPE_NONE, 2, TYPE_BACKGROUND_STATE, G_TYPE_UINT);
#line 276 "DBusServer.c"
}


static void wingpanel_interface_dbus_server_instance_init (WingpanelInterfaceDBusServer * self) {
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	self->priv = WINGPANEL_INTERFACE_DBUS_SERVER_GET_PRIVATE (self);
#line 283 "DBusServer.c"
}


static void wingpanel_interface_dbus_server_finalize (GObject* obj) {
	WingpanelInterfaceDBusServer * self;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WINGPANEL_INTERFACE_TYPE_DBUS_SERVER, WingpanelInterfaceDBusServer);
#line 22 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	_g_object_unref0 (self->priv->background_manager);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/DBusServer.vala"
	G_OBJECT_CLASS (wingpanel_interface_dbus_server_parent_class)->finalize (obj);
#line 295 "DBusServer.c"
}


GType wingpanel_interface_dbus_server_get_type (void) {
	static volatile gsize wingpanel_interface_dbus_server_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_interface_dbus_server_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelInterfaceDBusServerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_interface_dbus_server_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelInterfaceDBusServer), 0, (GInstanceInitFunc) wingpanel_interface_dbus_server_instance_init, NULL };
		GType wingpanel_interface_dbus_server_type_id;
		wingpanel_interface_dbus_server_type_id = g_type_register_static (G_TYPE_OBJECT, "WingpanelInterfaceDBusServer", &g_define_type_info, 0);
		g_type_set_qdata (wingpanel_interface_dbus_server_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) wingpanel_interface_dbus_server_register_object);
		g_once_init_leave (&wingpanel_interface_dbus_server_type_id__volatile, wingpanel_interface_dbus_server_type_id);
	}
	return wingpanel_interface_dbus_server_type_id__volatile;
}


static void _dbus_wingpanel_interface_dbus_server_initialize (WingpanelInterfaceDBusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	gint monitor = 0;
	GVariant* _tmp0_;
	gint panel_height = 0;
	GVariant* _tmp1_;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	_tmp0_ = g_variant_iter_next_value (&_arguments_iter);
	monitor = g_variant_get_int32 (_tmp0_);
	g_variant_unref (_tmp0_);
	_tmp1_ = g_variant_iter_next_value (&_arguments_iter);
	panel_height = g_variant_get_int32 (_tmp1_);
	g_variant_unref (_tmp1_);
	wingpanel_interface_dbus_server_initialize (self, monitor, panel_height);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_wingpanel_interface_dbus_server_remember_focused_window (WingpanelInterfaceDBusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	wingpanel_interface_dbus_server_remember_focused_window (self);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void _dbus_wingpanel_interface_dbus_server_restore_focused_window (WingpanelInterfaceDBusServer* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	wingpanel_interface_dbus_server_restore_focused_window (self);
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void wingpanel_interface_dbus_server_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "Initialize") == 0) {
		_dbus_wingpanel_interface_dbus_server_initialize (object, parameters, invocation);
	} else if (strcmp (method_name, "RememberFocusedWindow") == 0) {
		_dbus_wingpanel_interface_dbus_server_remember_focused_window (object, parameters, invocation);
	} else if (strcmp (method_name, "RestoreFocusedWindow") == 0) {
		_dbus_wingpanel_interface_dbus_server_restore_focused_window (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* wingpanel_interface_dbus_server_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean wingpanel_interface_dbus_server_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


static void _dbus_wingpanel_interface_dbus_server_state_changed (GObject* _sender, BackgroundState state, guint animation_duration, gpointer* _data) {
	GDBusConnection * _connection;
	const gchar * _path;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	_connection = _data[1];
	_path = _data[2];
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_int32 (state));
	g_variant_builder_add_value (&_arguments_builder, g_variant_new_uint32 (animation_duration));
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_connection_emit_signal (_connection, NULL, _path, "org.pantheon.gala.WingpanelInterface", "StateChanged", _arguments, NULL);
}


guint wingpanel_interface_dbus_server_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_wingpanel_interface_dbus_server_dbus_interface_info), &_wingpanel_interface_dbus_server_dbus_interface_vtable, data, _wingpanel_interface_dbus_server_unregister_object, error);
	if (!result) {
		return 0;
	}
	g_signal_connect (object, "state-changed", (GCallback) _dbus_wingpanel_interface_dbus_server_state_changed, data);
	return result;
}


static void _wingpanel_interface_dbus_server_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_signal_handlers_disconnect_by_func (data[0], _dbus_wingpanel_interface_dbus_server_state_changed, data);
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}



