/* Utils.c generated by valac 0.34.4, the Vala compiler
 * generated from Utils.vala, do not modify */

/*
 * Copyright (c) 2011-2015 Wingpanel Developers (http://launchpad.net/wingpanel)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */
/*
 *   The method for calculating the background information and the classes that are
 *   related to it are copied from Gala.DBus.
 */

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <clutter/clutter.h>
#include <string.h>
#include <gio/gio.h>
#include <gala.h>
#include <stdlib.h>
#include <cogl/cogl.h>


#define WINGPANEL_INTERFACE_UTILS_TYPE_DUMMY_OFFSCREEN_EFFECT (wingpanel_interface_utils_dummy_offscreen_effect_get_type ())
#define WINGPANEL_INTERFACE_UTILS_DUMMY_OFFSCREEN_EFFECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_INTERFACE_UTILS_TYPE_DUMMY_OFFSCREEN_EFFECT, WingpanelInterfaceUtilsDummyOffscreenEffect))
#define WINGPANEL_INTERFACE_UTILS_DUMMY_OFFSCREEN_EFFECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_INTERFACE_UTILS_TYPE_DUMMY_OFFSCREEN_EFFECT, WingpanelInterfaceUtilsDummyOffscreenEffectClass))
#define WINGPANEL_INTERFACE_UTILS_IS_DUMMY_OFFSCREEN_EFFECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_INTERFACE_UTILS_TYPE_DUMMY_OFFSCREEN_EFFECT))
#define WINGPANEL_INTERFACE_UTILS_IS_DUMMY_OFFSCREEN_EFFECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_INTERFACE_UTILS_TYPE_DUMMY_OFFSCREEN_EFFECT))
#define WINGPANEL_INTERFACE_UTILS_DUMMY_OFFSCREEN_EFFECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_INTERFACE_UTILS_TYPE_DUMMY_OFFSCREEN_EFFECT, WingpanelInterfaceUtilsDummyOffscreenEffectClass))

typedef struct _WingpanelInterfaceUtilsDummyOffscreenEffect WingpanelInterfaceUtilsDummyOffscreenEffect;
typedef struct _WingpanelInterfaceUtilsDummyOffscreenEffectClass WingpanelInterfaceUtilsDummyOffscreenEffectClass;
typedef struct _WingpanelInterfaceUtilsDummyOffscreenEffectPrivate WingpanelInterfaceUtilsDummyOffscreenEffectPrivate;

#define WINGPANEL_INTERFACE_UTILS_TYPE_COLOR_INFORMATION (wingpanel_interface_utils_color_information_get_type ())
typedef struct _WingpanelInterfaceUtilsColorInformation WingpanelInterfaceUtilsColorInformation;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block2Data Block2Data;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _cogl_texture_unref0(var) ((var == NULL) ? NULL : (var = (cogl_texture_unref (var), NULL)))
typedef struct _WingpanelInterfaceUtilsGetBackgroundColorInformationData WingpanelInterfaceUtilsGetBackgroundColorInformationData;

struct _WingpanelInterfaceUtilsDummyOffscreenEffect {
	ClutterOffscreenEffect parent_instance;
	WingpanelInterfaceUtilsDummyOffscreenEffectPrivate * priv;
};

struct _WingpanelInterfaceUtilsDummyOffscreenEffectClass {
	ClutterOffscreenEffectClass parent_class;
};

struct _WingpanelInterfaceUtilsColorInformation {
	gdouble average_red;
	gdouble average_green;
	gdouble average_blue;
	gdouble mean_luminance;
	gdouble luminance_variance;
	gdouble mean_acutance;
};

struct _Block2Data {
	int _ref_count_;
	ClutterActor* background;
	WingpanelInterfaceUtilsDummyOffscreenEffect* effect;
	gint x_start;
	gint y_start;
	gint width;
	gint height;
	gdouble mean_acutance;
	gdouble variance;
	gdouble mean;
	gdouble rTotal;
	gdouble gTotal;
	gdouble bTotal;
	gulong paint_signal_handler;
	gpointer _async_data_;
};

struct _WingpanelInterfaceUtilsGetBackgroundColorInformationData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	GalaWindowManager* wm;
	gint monitor;
	gint reference_x;
	gint reference_y;
	gint reference_width;
	gint reference_height;
	WingpanelInterfaceUtilsColorInformation result;
	Block2Data* _data2_;
	GalaWindowManager* _tmp0_;
	MetaBackgroundGroup* _tmp1_;
	MetaBackgroundGroup* _tmp2_;
	gint _tmp3_;
	ClutterActor* _tmp4_;
	ClutterActor* _tmp5_;
	ClutterActor* _tmp6_;
	gint _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	GError* _tmp10_;
	GError* _tmp11_;
	WingpanelInterfaceUtilsDummyOffscreenEffect* _tmp12_;
	ClutterActor* _tmp13_;
	WingpanelInterfaceUtilsDummyOffscreenEffect* _tmp14_;
	gint tex_width;
	ClutterActor* _tmp15_;
	gfloat _tmp16_;
	gfloat _tmp17_;
	gint tex_height;
	ClutterActor* _tmp18_;
	gfloat _tmp19_;
	gfloat _tmp20_;
	gint _tmp21_;
	gint _tmp22_;
	gint _tmp23_;
	gint _tmp24_;
	gint _tmp25_;
	gint _tmp26_;
	gint _tmp27_;
	gint _tmp28_;
	gint _tmp29_;
	gint _tmp30_;
	gboolean _tmp31_;
	gboolean _tmp32_;
	gboolean _tmp33_;
	gint _tmp34_;
	gint _tmp35_;
	gint _tmp36_;
	gint _tmp37_;
	gint _tmp38_;
	gint _tmp39_;
	gint _tmp40_;
	gint _tmp41_;
	gint _tmp42_;
	gint _tmp43_;
	gchar* _tmp44_;
	gchar* _tmp45_;
	GError* _tmp46_;
	GError* _tmp47_;
	WingpanelInterfaceUtilsDummyOffscreenEffect* _tmp48_;
	gulong _tmp49_;
	ClutterActor* _tmp50_;
	gdouble _tmp51_;
	gdouble _tmp52_;
	gdouble _tmp53_;
	gdouble _tmp54_;
	gdouble _tmp55_;
	gdouble _tmp56_;
	WingpanelInterfaceUtilsColorInformation _tmp57_;
	GError * _inner_error_;
};


static gpointer wingpanel_interface_utils_dummy_offscreen_effect_parent_class = NULL;

#define WINGPANEL_INTERFACE_UTILS_SATURATION_WEIGHT 1.5
#define WINGPANEL_INTERFACE_UTILS_WEIGHT_THRESHOLD 1.0
GType wingpanel_interface_utils_dummy_offscreen_effect_get_type (void) G_GNUC_CONST;
enum  {
	WINGPANEL_INTERFACE_UTILS_DUMMY_OFFSCREEN_EFFECT_DUMMY_PROPERTY
};
static void wingpanel_interface_utils_dummy_offscreen_effect_real_post_paint (ClutterEffect* base);
WingpanelInterfaceUtilsDummyOffscreenEffect* wingpanel_interface_utils_dummy_offscreen_effect_new (void);
WingpanelInterfaceUtilsDummyOffscreenEffect* wingpanel_interface_utils_dummy_offscreen_effect_construct (GType object_type);
GType wingpanel_interface_utils_color_information_get_type (void) G_GNUC_CONST;
WingpanelInterfaceUtilsColorInformation* wingpanel_interface_utils_color_information_dup (const WingpanelInterfaceUtilsColorInformation* self);
void wingpanel_interface_utils_color_information_free (WingpanelInterfaceUtilsColorInformation* self);
static void wingpanel_interface_utils_get_background_color_information_data_free (gpointer _data);
void wingpanel_interface_utils_get_background_color_information (GalaWindowManager* wm, gint monitor, gint reference_x, gint reference_y, gint reference_width, gint reference_height, GAsyncReadyCallback _callback_, gpointer _user_data_);
void wingpanel_interface_utils_get_background_color_information_finish (GAsyncResult* _res_, WingpanelInterfaceUtilsColorInformation* result, GError** error);
static gboolean wingpanel_interface_utils_get_background_color_information_co (WingpanelInterfaceUtilsGetBackgroundColorInformationData* _data_);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda8_ (Block2Data* _data2_);
static void ___lambda8__wingpanel_interface_utils_dummy_offscreen_effect_done_painting (WingpanelInterfaceUtilsDummyOffscreenEffect* _sender, gpointer self);


static void wingpanel_interface_utils_dummy_offscreen_effect_real_post_paint (ClutterEffect* base) {
	WingpanelInterfaceUtilsDummyOffscreenEffect * self;
#line 32 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	self = (WingpanelInterfaceUtilsDummyOffscreenEffect*) base;
#line 33 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	CLUTTER_EFFECT_CLASS (wingpanel_interface_utils_dummy_offscreen_effect_parent_class)->post_paint ((ClutterEffect*) G_TYPE_CHECK_INSTANCE_CAST (self, clutter_offscreen_effect_get_type (), ClutterOffscreenEffect));
#line 34 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	g_signal_emit_by_name (self, "done-painting");
#line 204 "Utils.c"
}


WingpanelInterfaceUtilsDummyOffscreenEffect* wingpanel_interface_utils_dummy_offscreen_effect_construct (GType object_type) {
	WingpanelInterfaceUtilsDummyOffscreenEffect * self = NULL;
#line 29 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	self = (WingpanelInterfaceUtilsDummyOffscreenEffect*) g_object_new (object_type, NULL);
#line 29 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	return self;
#line 214 "Utils.c"
}


WingpanelInterfaceUtilsDummyOffscreenEffect* wingpanel_interface_utils_dummy_offscreen_effect_new (void) {
#line 29 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	return wingpanel_interface_utils_dummy_offscreen_effect_construct (WINGPANEL_INTERFACE_UTILS_TYPE_DUMMY_OFFSCREEN_EFFECT);
#line 221 "Utils.c"
}


static void wingpanel_interface_utils_dummy_offscreen_effect_class_init (WingpanelInterfaceUtilsDummyOffscreenEffectClass * klass) {
#line 29 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	wingpanel_interface_utils_dummy_offscreen_effect_parent_class = g_type_class_peek_parent (klass);
#line 29 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	((ClutterEffectClass *) klass)->post_paint = wingpanel_interface_utils_dummy_offscreen_effect_real_post_paint;
#line 29 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	g_signal_new ("done_painting", WINGPANEL_INTERFACE_UTILS_TYPE_DUMMY_OFFSCREEN_EFFECT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 232 "Utils.c"
}


static void wingpanel_interface_utils_dummy_offscreen_effect_instance_init (WingpanelInterfaceUtilsDummyOffscreenEffect * self) {
}


GType wingpanel_interface_utils_dummy_offscreen_effect_get_type (void) {
	static volatile gsize wingpanel_interface_utils_dummy_offscreen_effect_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_interface_utils_dummy_offscreen_effect_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelInterfaceUtilsDummyOffscreenEffectClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_interface_utils_dummy_offscreen_effect_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelInterfaceUtilsDummyOffscreenEffect), 0, (GInstanceInitFunc) wingpanel_interface_utils_dummy_offscreen_effect_instance_init, NULL };
		GType wingpanel_interface_utils_dummy_offscreen_effect_type_id;
		wingpanel_interface_utils_dummy_offscreen_effect_type_id = g_type_register_static (clutter_offscreen_effect_get_type (), "WingpanelInterfaceUtilsDummyOffscreenEffect", &g_define_type_info, 0);
		g_once_init_leave (&wingpanel_interface_utils_dummy_offscreen_effect_type_id__volatile, wingpanel_interface_utils_dummy_offscreen_effect_type_id);
	}
	return wingpanel_interface_utils_dummy_offscreen_effect_type_id__volatile;
}


WingpanelInterfaceUtilsColorInformation* wingpanel_interface_utils_color_information_dup (const WingpanelInterfaceUtilsColorInformation* self) {
	WingpanelInterfaceUtilsColorInformation* dup;
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	dup = g_new0 (WingpanelInterfaceUtilsColorInformation, 1);
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	memcpy (dup, self, sizeof (WingpanelInterfaceUtilsColorInformation));
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	return dup;
#line 260 "Utils.c"
}


void wingpanel_interface_utils_color_information_free (WingpanelInterfaceUtilsColorInformation* self) {
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	g_free (self);
#line 267 "Utils.c"
}


GType wingpanel_interface_utils_color_information_get_type (void) {
	static volatile gsize wingpanel_interface_utils_color_information_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_interface_utils_color_information_type_id__volatile)) {
		GType wingpanel_interface_utils_color_information_type_id;
		wingpanel_interface_utils_color_information_type_id = g_boxed_type_register_static ("WingpanelInterfaceUtilsColorInformation", (GBoxedCopyFunc) wingpanel_interface_utils_color_information_dup, (GBoxedFreeFunc) wingpanel_interface_utils_color_information_free);
		g_once_init_leave (&wingpanel_interface_utils_color_information_type_id__volatile, wingpanel_interface_utils_color_information_type_id);
	}
	return wingpanel_interface_utils_color_information_type_id__volatile;
}


static void wingpanel_interface_utils_get_background_color_information_data_free (gpointer _data) {
	WingpanelInterfaceUtilsGetBackgroundColorInformationData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->wm);
	g_slice_free (WingpanelInterfaceUtilsGetBackgroundColorInformationData, _data_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void wingpanel_interface_utils_get_background_color_information (GalaWindowManager* wm, gint monitor, gint reference_x, gint reference_y, gint reference_width, gint reference_height, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	WingpanelInterfaceUtilsGetBackgroundColorInformationData* _data_;
	GalaWindowManager* _tmp0_ = NULL;
	GalaWindowManager* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	_data_ = g_slice_new0 (WingpanelInterfaceUtilsGetBackgroundColorInformationData);
	_data_->_async_result = g_simple_async_result_new (NULL, _callback_, _user_data_, wingpanel_interface_utils_get_background_color_information);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, wingpanel_interface_utils_get_background_color_information_data_free);
	_tmp0_ = wm;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (_data_->wm);
	_data_->wm = _tmp1_;
	_tmp2_ = monitor;
	_data_->monitor = _tmp2_;
	_tmp3_ = reference_x;
	_data_->reference_x = _tmp3_;
	_tmp4_ = reference_y;
	_data_->reference_y = _tmp4_;
	_tmp5_ = reference_width;
	_data_->reference_width = _tmp5_;
	_tmp6_ = reference_height;
	_data_->reference_height = _tmp6_;
	wingpanel_interface_utils_get_background_color_information_co (_data_);
}


void wingpanel_interface_utils_get_background_color_information_finish (GAsyncResult* _res_, WingpanelInterfaceUtilsColorInformation* result, GError** error) {
	WingpanelInterfaceUtilsGetBackgroundColorInformationData* _data_;
	if (g_simple_async_result_propagate_error (G_SIMPLE_ASYNC_RESULT (_res_), error)) {
		return;
	}
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
	*result = _data_->result;
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	return _data2_;
#line 340 "Utils.c"
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_g_object_unref0 (_data2_->effect);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_g_object_unref0 (_data2_->background);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		g_slice_free (Block2Data, _data2_);
#line 355 "Utils.c"
	}
}


static gpointer _cogl_texture_ref0 (gpointer self) {
#line 77 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	return self ? cogl_texture_ref (self) : NULL;
#line 363 "Utils.c"
}


static void __lambda8_ (Block2Data* _data2_) {
	WingpanelInterfaceUtilsDummyOffscreenEffect* _tmp0_ = NULL;
	gulong _tmp1_ = 0UL;
	ClutterActor* _tmp2_ = NULL;
	WingpanelInterfaceUtilsDummyOffscreenEffect* _tmp3_ = NULL;
	CoglHandle* texture = NULL;
	WingpanelInterfaceUtilsDummyOffscreenEffect* _tmp4_ = NULL;
	CoglHandle* _tmp5_ = NULL;
	CoglHandle* _tmp6_ = NULL;
	guint8* pixels = NULL;
	CoglHandle* _tmp7_ = NULL;
	guint _tmp8_ = 0U;
	CoglHandle* _tmp9_ = NULL;
	guint _tmp10_ = 0U;
	guint8* _tmp11_ = NULL;
	gint pixels_length1 = 0;
	gint _pixels_size_ = 0;
	gdouble* pixel_lums = NULL;
	CoglHandle* _tmp12_ = NULL;
	guint _tmp13_ = 0U;
	CoglHandle* _tmp14_ = NULL;
	guint _tmp15_ = 0U;
	gdouble* _tmp16_ = NULL;
	gint pixel_lums_length1 = 0;
	gint _pixel_lums_size_ = 0;
	CoglHandle* _tmp17_ = NULL;
	guint8* _tmp18_ = NULL;
	gint _tmp18__length1 = 0;
	gint size = 0;
	gint _tmp19_ = 0;
	gint _tmp20_ = 0;
	gdouble mean_squares = 0.0;
	gdouble pixel = 0.0;
	gdouble max = 0.0;
	gdouble min = 0.0;
	gdouble score = 0.0;
	gdouble delta = 0.0;
	gdouble scoreTotal = 0.0;
	gdouble rTotal2 = 0.0;
	gdouble gTotal2 = 0.0;
	gdouble bTotal2 = 0.0;
	gdouble _tmp130_ = 0.0;
	gint _tmp131_ = 0;
	gdouble _tmp132_ = 0.0;
	gint _tmp133_ = 0;
	gdouble _tmp134_ = 0.0;
	gint _tmp135_ = 0;
	gdouble _tmp136_ = 0.0;
	gint _tmp137_ = 0;
	gdouble _tmp138_ = 0.0;
	gdouble _tmp145_ = 0.0;
	gint _tmp146_ = 0;
	gdouble _tmp147_ = 0.0;
	gint _tmp148_ = 0;
	gdouble _tmp149_ = 0.0;
	gint _tmp150_ = 0;
	gdouble _tmp151_ = 0.0;
	gdouble max_val = 0.0;
	gdouble _tmp166_ = 0.0;
	gdouble _tmp167_ = 0.0;
	gdouble _tmp168_ = 0.0;
	gdouble _tmp169_ = 0.0;
	gdouble _tmp170_ = 0.0;
	gdouble _tmp171_ = 0.0;
	gdouble _tmp178_ = 0.0;
	gint _tmp179_ = 0;
	gdouble _tmp180_ = 0.0;
	gint _tmp181_ = 0;
	gdouble _tmp182_ = 0.0;
	gdouble _tmp183_ = 0.0;
	gdouble _tmp184_ = 0.0;
	gdouble _tmp185_ = 0.0;
	gint _tmp186_ = 0;
	gint _tmp187_ = 0;
#line 74 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp0_ = _data2_->effect;
#line 74 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp1_ = _data2_->paint_signal_handler;
#line 74 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	g_signal_handler_disconnect (_tmp0_, _tmp1_);
#line 75 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp2_ = _data2_->background;
#line 75 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp3_ = _data2_->effect;
#line 75 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	clutter_actor_remove_effect (_tmp2_, (ClutterEffect*) _tmp3_);
#line 77 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp4_ = _data2_->effect;
#line 77 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp5_ = clutter_offscreen_effect_get_texture ((ClutterOffscreenEffect*) _tmp4_);
#line 77 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp6_ = _cogl_texture_ref0 ((CoglHandle*) _tmp5_);
#line 77 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	texture = _tmp6_;
#line 78 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp7_ = texture;
#line 78 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp8_ = cogl_texture_get_width (_tmp7_);
#line 78 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp9_ = texture;
#line 78 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp10_ = cogl_texture_get_height (_tmp9_);
#line 78 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp11_ = g_new0 (guint8, (_tmp8_ * _tmp10_) * 4);
#line 78 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	pixels = _tmp11_;
#line 78 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	pixels_length1 = (_tmp8_ * _tmp10_) * 4;
#line 78 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_pixels_size_ = pixels_length1;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp12_ = texture;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp13_ = cogl_texture_get_width (_tmp12_);
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp14_ = texture;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp15_ = cogl_texture_get_height (_tmp14_);
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp16_ = g_new0 (gdouble, _tmp13_ * _tmp15_);
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	pixel_lums = _tmp16_;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	pixel_lums_length1 = _tmp13_ * _tmp15_;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_pixel_lums_size_ = pixel_lums_length1;
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp17_ = texture;
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp18_ = pixels;
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp18__length1 = pixels_length1;
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	cogl_texture_get_data (_tmp17_, COGL_PIXEL_FORMAT_BGRA_8888_PRE, (guint) 0, _tmp18_);
#line 83 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp19_ = _data2_->width;
#line 83 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp20_ = _data2_->height;
#line 83 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	size = _tmp19_ * _tmp20_;
#line 85 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	mean_squares = (gdouble) 0;
#line 86 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	pixel = (gdouble) 0;
#line 88 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	scoreTotal = (gdouble) 0;
#line 88 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	rTotal2 = (gdouble) 0;
#line 88 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	gTotal2 = (gdouble) 0;
#line 88 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	bTotal2 = (gdouble) 0;
#line 519 "Utils.c"
	{
		gint y = 0;
		gint _tmp21_ = 0;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp21_ = _data2_->y_start;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		y = _tmp21_;
#line 527 "Utils.c"
		{
			gboolean _tmp22_ = FALSE;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			_tmp22_ = TRUE;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			while (TRUE) {
#line 534 "Utils.c"
				gint _tmp24_ = 0;
				gint _tmp25_ = 0;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				if (!_tmp22_) {
#line 539 "Utils.c"
					gint _tmp23_ = 0;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					_tmp23_ = y;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					y = _tmp23_ + 1;
#line 545 "Utils.c"
				}
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				_tmp22_ = FALSE;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				_tmp24_ = y;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				_tmp25_ = _data2_->height;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				if (!(_tmp24_ < _tmp25_)) {
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					break;
#line 557 "Utils.c"
				}
				{
					gint x = 0;
					gint _tmp26_ = 0;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					_tmp26_ = _data2_->x_start;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					x = _tmp26_;
#line 566 "Utils.c"
					{
						gboolean _tmp27_ = FALSE;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
						_tmp27_ = TRUE;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
						while (TRUE) {
#line 573 "Utils.c"
							gint _tmp29_ = 0;
							gint _tmp30_ = 0;
							gint i = 0;
							gint _tmp31_ = 0;
							gint _tmp32_ = 0;
							gint _tmp33_ = 0;
							guint8 r = 0U;
							guint8* _tmp34_ = NULL;
							gint _tmp34__length1 = 0;
							gint _tmp35_ = 0;
							guint8 _tmp36_ = 0U;
							guint8 g = 0U;
							guint8* _tmp37_ = NULL;
							gint _tmp37__length1 = 0;
							gint _tmp38_ = 0;
							guint8 _tmp39_ = 0U;
							guint8 b = 0U;
							guint8* _tmp40_ = NULL;
							gint _tmp40__length1 = 0;
							gint _tmp41_ = 0;
							guint8 _tmp42_ = 0U;
							guint8 _tmp43_ = 0U;
							guint8 _tmp44_ = 0U;
							guint8 _tmp45_ = 0U;
							gdouble* _tmp46_ = NULL;
							gint _tmp46__length1 = 0;
							gint _tmp47_ = 0;
							gint _tmp48_ = 0;
							gint _tmp49_ = 0;
							gdouble _tmp50_ = 0.0;
							gdouble _tmp51_ = 0.0;
							guint8 _tmp52_ = 0U;
							guint8 _tmp53_ = 0U;
							guint8 _tmp54_ = 0U;
							guint8 _tmp55_ = 0U;
							guint8 _tmp56_ = 0U;
							guint8 _tmp57_ = 0U;
							guint8 _tmp58_ = 0U;
							guint8 _tmp59_ = 0U;
							guint8 _tmp60_ = 0U;
							guint8 _tmp61_ = 0U;
							gdouble _tmp62_ = 0.0;
							gdouble _tmp63_ = 0.0;
							gdouble _tmp64_ = 0.0;
							gdouble _tmp65_ = 0.0;
							gdouble _tmp68_ = 0.0;
							gdouble _tmp69_ = 0.0;
							guint8 _tmp70_ = 0U;
							gdouble _tmp71_ = 0.0;
							gdouble _tmp72_ = 0.0;
							guint8 _tmp73_ = 0U;
							gdouble _tmp74_ = 0.0;
							gdouble _tmp75_ = 0.0;
							guint8 _tmp76_ = 0U;
							gdouble _tmp77_ = 0.0;
							gdouble _tmp78_ = 0.0;
							gdouble _tmp79_ = 0.0;
							guint8 _tmp80_ = 0U;
							gdouble _tmp81_ = 0.0;
							guint8 _tmp82_ = 0U;
							gdouble _tmp83_ = 0.0;
							guint8 _tmp84_ = 0U;
							gdouble _tmp85_ = 0.0;
							gdouble _tmp86_ = 0.0;
							gdouble _tmp87_ = 0.0;
							gdouble _tmp88_ = 0.0;
							gdouble _tmp89_ = 0.0;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							if (!_tmp27_) {
#line 643 "Utils.c"
								gint _tmp28_ = 0;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp28_ = x;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								x = _tmp28_ + 1;
#line 649 "Utils.c"
							}
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp27_ = FALSE;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp29_ = x;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp30_ = _data2_->width;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							if (!(_tmp29_ < _tmp30_)) {
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								break;
#line 661 "Utils.c"
							}
#line 97 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp31_ = y;
#line 97 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp32_ = _data2_->width;
#line 97 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp33_ = x;
#line 97 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							i = ((_tmp31_ * _tmp32_) * 4) + (_tmp33_ * 4);
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp34_ = pixels;
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp34__length1 = pixels_length1;
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp35_ = i;
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp36_ = _tmp34_[_tmp35_];
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							r = _tmp36_;
#line 100 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp37_ = pixels;
#line 100 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp37__length1 = pixels_length1;
#line 100 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp38_ = i;
#line 100 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp39_ = _tmp37_[_tmp38_ + 1];
#line 100 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							g = _tmp39_;
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp40_ = pixels;
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp40__length1 = pixels_length1;
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp41_ = i;
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp42_ = _tmp40_[_tmp41_ + 2];
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							b = _tmp42_;
#line 103 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp43_ = r;
#line 103 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp44_ = g;
#line 103 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp45_ = b;
#line 103 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							pixel = ((0.3 * _tmp43_) + (0.59 * _tmp44_)) + (0.11 * _tmp45_);
#line 105 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp46_ = pixel_lums;
#line 105 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp46__length1 = pixel_lums_length1;
#line 105 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp47_ = y;
#line 105 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp48_ = _data2_->width;
#line 105 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp49_ = x;
#line 105 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp50_ = pixel;
#line 105 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp46_[(_tmp47_ * _tmp48_) + _tmp49_] = _tmp50_;
#line 105 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp51_ = _tmp46_[(_tmp47_ * _tmp48_) + _tmp49_];
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp52_ = r;
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp53_ = g;
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp54_ = b;
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp55_ = MIN (_tmp53_, _tmp54_);
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp56_ = MIN (_tmp52_, _tmp55_);
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							min = (gdouble) _tmp56_;
#line 108 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp57_ = r;
#line 108 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp58_ = g;
#line 108 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp59_ = b;
#line 108 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp60_ = MAX (_tmp58_, _tmp59_);
#line 108 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp61_ = MAX (_tmp57_, _tmp60_);
#line 108 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							max = (gdouble) _tmp61_;
#line 110 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp62_ = max;
#line 110 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp63_ = min;
#line 110 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							delta = _tmp62_ - _tmp63_;
#line 113 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp65_ = delta;
#line 113 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							if (_tmp65_ == ((gdouble) 0)) {
#line 113 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp64_ = 0.0;
#line 761 "Utils.c"
							} else {
								gdouble _tmp66_ = 0.0;
								gdouble _tmp67_ = 0.0;
#line 113 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp66_ = delta;
#line 113 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp67_ = max;
#line 113 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp64_ = _tmp66_ / _tmp67_;
#line 771 "Utils.c"
							}
#line 113 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							score = WINGPANEL_INTERFACE_UTILS_SATURATION_WEIGHT * _tmp64_;
#line 115 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp68_ = _data2_->rTotal;
#line 115 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp69_ = score;
#line 115 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp70_ = r;
#line 115 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_data2_->rTotal = _tmp68_ + (_tmp69_ * _tmp70_);
#line 116 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp71_ = _data2_->gTotal;
#line 116 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp72_ = score;
#line 116 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp73_ = g;
#line 116 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_data2_->gTotal = _tmp71_ + (_tmp72_ * _tmp73_);
#line 117 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp74_ = _data2_->bTotal;
#line 117 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp75_ = score;
#line 117 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp76_ = b;
#line 117 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_data2_->bTotal = _tmp74_ + (_tmp75_ * _tmp76_);
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp77_ = scoreTotal;
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp78_ = score;
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							scoreTotal = _tmp77_ + _tmp78_;
#line 120 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp79_ = _data2_->rTotal;
#line 120 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp80_ = r;
#line 120 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_data2_->rTotal = _tmp79_ + _tmp80_;
#line 121 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp81_ = _data2_->gTotal;
#line 121 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp82_ = g;
#line 121 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_data2_->gTotal = _tmp81_ + _tmp82_;
#line 122 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp83_ = _data2_->bTotal;
#line 122 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp84_ = b;
#line 122 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_data2_->bTotal = _tmp83_ + _tmp84_;
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp85_ = _data2_->mean;
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp86_ = pixel;
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_data2_->mean = _tmp85_ + _tmp86_;
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp87_ = mean_squares;
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp88_ = pixel;
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp89_ = pixel;
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							mean_squares = _tmp87_ + (_tmp88_ * _tmp89_);
#line 837 "Utils.c"
						}
					}
				}
			}
		}
	}
	{
		gint y = 0;
		gint _tmp90_ = 0;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp90_ = _data2_->y_start;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		y = _tmp90_ + 1;
#line 851 "Utils.c"
		{
			gboolean _tmp91_ = FALSE;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			_tmp91_ = TRUE;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			while (TRUE) {
#line 858 "Utils.c"
				gint _tmp93_ = 0;
				gint _tmp94_ = 0;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				if (!_tmp91_) {
#line 863 "Utils.c"
					gint _tmp92_ = 0;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					_tmp92_ = y;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					y = _tmp92_ + 1;
#line 869 "Utils.c"
				}
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				_tmp91_ = FALSE;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				_tmp93_ = y;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				_tmp94_ = _data2_->height;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				if (!(_tmp93_ < (_tmp94_ - 1))) {
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					break;
#line 881 "Utils.c"
				}
				{
					gint x = 0;
					gint _tmp95_ = 0;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					_tmp95_ = _data2_->x_start;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
					x = _tmp95_ + 1;
#line 890 "Utils.c"
					{
						gboolean _tmp96_ = FALSE;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
						_tmp96_ = TRUE;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
						while (TRUE) {
#line 897 "Utils.c"
							gint _tmp98_ = 0;
							gint _tmp99_ = 0;
							gdouble acutance = 0.0;
							gdouble* _tmp100_ = NULL;
							gint _tmp100__length1 = 0;
							gint _tmp101_ = 0;
							gint _tmp102_ = 0;
							gint _tmp103_ = 0;
							gdouble _tmp104_ = 0.0;
							gdouble* _tmp105_ = NULL;
							gint _tmp105__length1 = 0;
							gint _tmp106_ = 0;
							gint _tmp107_ = 0;
							gint _tmp108_ = 0;
							gdouble _tmp109_ = 0.0;
							gdouble* _tmp110_ = NULL;
							gint _tmp110__length1 = 0;
							gint _tmp111_ = 0;
							gint _tmp112_ = 0;
							gint _tmp113_ = 0;
							gdouble _tmp114_ = 0.0;
							gdouble* _tmp115_ = NULL;
							gint _tmp115__length1 = 0;
							gint _tmp116_ = 0;
							gint _tmp117_ = 0;
							gint _tmp118_ = 0;
							gdouble _tmp119_ = 0.0;
							gdouble* _tmp120_ = NULL;
							gint _tmp120__length1 = 0;
							gint _tmp121_ = 0;
							gint _tmp122_ = 0;
							gint _tmp123_ = 0;
							gdouble _tmp124_ = 0.0;
							gdouble _tmp125_ = 0.0;
							gdouble _tmp126_ = 0.0;
							gdouble _tmp129_ = 0.0;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							if (!_tmp96_) {
#line 936 "Utils.c"
								gint _tmp97_ = 0;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp97_ = x;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								x = _tmp97_ + 1;
#line 942 "Utils.c"
							}
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp96_ = FALSE;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp98_ = x;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp99_ = _data2_->width;
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							if (!(_tmp98_ < (_tmp99_ - 1))) {
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								break;
#line 954 "Utils.c"
							}
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp100_ = pixel_lums;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp100__length1 = pixel_lums_length1;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp101_ = y;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp102_ = _data2_->width;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp103_ = x;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp104_ = _tmp100_[(_tmp101_ * _tmp102_) + _tmp103_];
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp105_ = pixel_lums;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp105__length1 = pixel_lums_length1;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp106_ = y;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp107_ = _data2_->width;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp108_ = x;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp109_ = _tmp105_[((_tmp106_ * _tmp107_) + _tmp108_) - 1];
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp110_ = pixel_lums;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp110__length1 = pixel_lums_length1;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp111_ = y;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp112_ = _data2_->width;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp113_ = x;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp114_ = _tmp110_[((_tmp111_ * _tmp112_) + _tmp113_) + 1];
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp115_ = pixel_lums;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp115__length1 = pixel_lums_length1;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp116_ = y;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp117_ = _data2_->width;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp118_ = x;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp119_ = _tmp115_[((_tmp116_ - 1) * _tmp117_) + _tmp118_];
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp120_ = pixel_lums;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp120__length1 = pixel_lums_length1;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp121_ = y;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp122_ = _data2_->width;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp123_ = x;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp124_ = _tmp120_[((_tmp121_ + 1) * _tmp122_) + _tmp123_];
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							acutance = (_tmp104_ * 4) - (((_tmp109_ + _tmp114_) + _tmp119_) + _tmp124_);
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp126_ = acutance;
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							if (_tmp126_ > ((gdouble) 0)) {
#line 1022 "Utils.c"
								gdouble _tmp127_ = 0.0;
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp127_ = acutance;
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp125_ = _tmp127_;
#line 1028 "Utils.c"
							} else {
								gdouble _tmp128_ = 0.0;
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp128_ = acutance;
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
								_tmp125_ = -_tmp128_;
#line 1035 "Utils.c"
							}
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_tmp129_ = _data2_->mean_acutance;
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
							_data2_->mean_acutance = _tmp129_ + _tmp125_;
#line 1041 "Utils.c"
						}
					}
				}
			}
		}
	}
#line 144 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp130_ = scoreTotal;
#line 144 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp131_ = size;
#line 144 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	scoreTotal = _tmp130_ / _tmp131_;
#line 145 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp132_ = _data2_->bTotal;
#line 145 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp133_ = size;
#line 145 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data2_->bTotal = _tmp132_ / _tmp133_;
#line 146 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp134_ = _data2_->gTotal;
#line 146 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp135_ = size;
#line 146 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data2_->gTotal = _tmp134_ / _tmp135_;
#line 147 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp136_ = _data2_->rTotal;
#line 147 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp137_ = size;
#line 147 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data2_->rTotal = _tmp136_ / _tmp137_;
#line 149 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp138_ = scoreTotal;
#line 149 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_tmp138_ > 0.0) {
#line 1076 "Utils.c"
		gdouble _tmp139_ = 0.0;
		gdouble _tmp140_ = 0.0;
		gdouble _tmp141_ = 0.0;
		gdouble _tmp142_ = 0.0;
		gdouble _tmp143_ = 0.0;
		gdouble _tmp144_ = 0.0;
#line 150 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp139_ = _data2_->bTotal;
#line 150 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp140_ = scoreTotal;
#line 150 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data2_->bTotal = _tmp139_ / _tmp140_;
#line 151 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp141_ = _data2_->gTotal;
#line 151 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp142_ = scoreTotal;
#line 151 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data2_->gTotal = _tmp141_ / _tmp142_;
#line 152 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp143_ = _data2_->rTotal;
#line 152 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp144_ = scoreTotal;
#line 152 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data2_->rTotal = _tmp143_ / _tmp144_;
#line 1101 "Utils.c"
	}
#line 155 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp145_ = bTotal2;
#line 155 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp146_ = size;
#line 155 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	bTotal2 = _tmp145_ / (_tmp146_ * G_MAXUINT8);
#line 156 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp147_ = gTotal2;
#line 156 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp148_ = size;
#line 156 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	gTotal2 = _tmp147_ / (_tmp148_ * G_MAXUINT8);
#line 157 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp149_ = rTotal2;
#line 157 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp150_ = size;
#line 157 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	rTotal2 = _tmp149_ / (_tmp150_ * G_MAXUINT8);
#line 164 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp151_ = scoreTotal;
#line 164 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_tmp151_ <= WINGPANEL_INTERFACE_UTILS_WEIGHT_THRESHOLD) {
#line 1125 "Utils.c"
		gdouble f = 0.0;
		gdouble _tmp152_ = 0.0;
		gdouble rf = 0.0;
		gdouble _tmp153_ = 0.0;
		gdouble _tmp154_ = 0.0;
		gdouble _tmp155_ = 0.0;
		gdouble _tmp156_ = 0.0;
		gdouble _tmp157_ = 0.0;
		gdouble _tmp158_ = 0.0;
		gdouble _tmp159_ = 0.0;
		gdouble _tmp160_ = 0.0;
		gdouble _tmp161_ = 0.0;
		gdouble _tmp162_ = 0.0;
		gdouble _tmp163_ = 0.0;
		gdouble _tmp164_ = 0.0;
		gdouble _tmp165_ = 0.0;
#line 165 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp152_ = scoreTotal;
#line 165 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		f = (1.0 / WINGPANEL_INTERFACE_UTILS_WEIGHT_THRESHOLD) * _tmp152_;
#line 166 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp153_ = f;
#line 166 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		rf = 1.0 - _tmp153_;
#line 168 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp154_ = _data2_->bTotal;
#line 168 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp155_ = f;
#line 168 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp156_ = bTotal2;
#line 168 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp157_ = rf;
#line 168 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data2_->bTotal = (_tmp154_ * _tmp155_) + (_tmp156_ * _tmp157_);
#line 169 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp158_ = _data2_->gTotal;
#line 169 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp159_ = f;
#line 169 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp160_ = gTotal2;
#line 169 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp161_ = rf;
#line 169 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data2_->gTotal = (_tmp158_ * _tmp159_) + (_tmp160_ * _tmp161_);
#line 170 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp162_ = _data2_->rTotal;
#line 170 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp163_ = f;
#line 170 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp164_ = rTotal2;
#line 170 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp165_ = rf;
#line 170 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data2_->rTotal = (_tmp162_ * _tmp163_) + (_tmp164_ * _tmp165_);
#line 1180 "Utils.c"
	}
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp166_ = _data2_->rTotal;
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp167_ = _data2_->gTotal;
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp168_ = _data2_->bTotal;
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp169_ = MAX (_tmp167_, _tmp168_);
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp170_ = MAX (_tmp166_, _tmp169_);
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	max_val = _tmp170_;
#line 176 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp171_ = max_val;
#line 176 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_tmp171_ > 1.0) {
#line 1198 "Utils.c"
		gdouble _tmp172_ = 0.0;
		gdouble _tmp173_ = 0.0;
		gdouble _tmp174_ = 0.0;
		gdouble _tmp175_ = 0.0;
		gdouble _tmp176_ = 0.0;
		gdouble _tmp177_ = 0.0;
#line 177 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp172_ = _data2_->bTotal;
#line 177 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp173_ = max_val;
#line 177 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data2_->bTotal = _tmp172_ / _tmp173_;
#line 178 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp174_ = _data2_->gTotal;
#line 178 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp175_ = max_val;
#line 178 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data2_->gTotal = _tmp174_ / _tmp175_;
#line 179 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp176_ = _data2_->rTotal;
#line 179 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_tmp177_ = max_val;
#line 179 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data2_->rTotal = _tmp176_ / _tmp177_;
#line 1223 "Utils.c"
	}
#line 182 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp178_ = _data2_->mean;
#line 182 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp179_ = size;
#line 182 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data2_->mean = _tmp178_ / _tmp179_;
#line 183 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp180_ = mean_squares;
#line 183 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp181_ = size;
#line 183 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	mean_squares = _tmp180_ / _tmp181_;
#line 185 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp182_ = mean_squares;
#line 185 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp183_ = _data2_->mean;
#line 185 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp184_ = _data2_->mean;
#line 185 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data2_->variance = _tmp182_ - (_tmp183_ * _tmp184_);
#line 187 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp185_ = _data2_->mean_acutance;
#line 187 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp186_ = _data2_->width;
#line 187 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_tmp187_ = _data2_->height;
#line 187 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data2_->mean_acutance = _tmp185_ / ((_tmp186_ - 2) * (_tmp187_ - 2));
#line 189 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	wingpanel_interface_utils_get_background_color_information_co (_data2_->_async_data_);
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	pixel_lums = (g_free (pixel_lums), NULL);
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	pixels = (g_free (pixels), NULL);
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_cogl_texture_unref0 (texture);
#line 1261 "Utils.c"
}


static void ___lambda8__wingpanel_interface_utils_dummy_offscreen_effect_done_painting (WingpanelInterfaceUtilsDummyOffscreenEffect* _sender, gpointer self) {
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	__lambda8_ (self);
#line 1268 "Utils.c"
}


static gboolean wingpanel_interface_utils_get_background_color_information_co (WingpanelInterfaceUtilsGetBackgroundColorInformationData* _data_) {
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	switch (_data_->_state_) {
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		case 0:
#line 1277 "Utils.c"
		goto _state_0;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		case 1:
#line 1281 "Utils.c"
		goto _state_1;
		default:
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		g_assert_not_reached ();
#line 1286 "Utils.c"
	}
	_state_0:
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_ = g_slice_new0 (Block2Data);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->_ref_count_ = 1;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->_async_data_ = _data_;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp0_ = NULL;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp0_ = _data_->wm;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp1_ = NULL;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp1_ = gala_window_manager_get_background_group (_data_->_tmp0_);
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp2_ = NULL;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp2_ = _data_->_tmp1_;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp3_ = 0;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp3_ = _data_->monitor;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp4_ = NULL;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp4_ = clutter_actor_get_child_at_index ((ClutterActor*) _data_->_tmp2_, _data_->_tmp3_);
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp5_ = NULL;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp5_ = _g_object_ref0 (_data_->_tmp4_);
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->background = _data_->_tmp5_;
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp6_ = NULL;
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp6_ = _data_->_data2_->background;
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_data_->_tmp6_ == NULL) {
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp7_ = 0;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp7_ = _data_->monitor;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp8_ = NULL;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp8_ = g_strdup_printf ("Invalid monitor requested: %i", _data_->_tmp7_);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp9_ = NULL;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp9_ = _data_->_tmp8_;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp10_ = NULL;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp10_ = g_error_new_literal (G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, _data_->_tmp9_);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp11_ = NULL;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp11_ = _data_->_tmp10_;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_g_free0 (_data_->_tmp9_);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_inner_error_ = _data_->_tmp11_;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		if (_data_->_inner_error_->domain == G_DBUS_ERROR) {
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_simple_async_result_set_from_error (_data_->_async_result, _data_->_inner_error_);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_error_free (_data_->_inner_error_);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			block2_data_unref (_data_->_data2_);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			_data_->_data2_ = NULL;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			if (_data_->_state_ == 0) {
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 1365 "Utils.c"
			} else {
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				g_simple_async_result_complete (_data_->_async_result);
#line 1369 "Utils.c"
			}
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_object_unref (_data_->_async_result);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			return FALSE;
#line 1375 "Utils.c"
		} else {
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			block2_data_unref (_data_->_data2_);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			_data_->_data2_ = NULL;
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_clear_error (&_data_->_inner_error_);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			return FALSE;
#line 1387 "Utils.c"
		}
	}
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp12_ = NULL;
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp12_ = wingpanel_interface_utils_dummy_offscreen_effect_new ();
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	g_object_ref_sink (_data_->_tmp12_);
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->effect = _data_->_tmp12_;
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp13_ = NULL;
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp13_ = _data_->_data2_->background;
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp14_ = NULL;
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp14_ = _data_->_data2_->effect;
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	clutter_actor_add_effect (_data_->_tmp13_, (ClutterEffect*) _data_->_tmp14_);
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp15_ = NULL;
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp15_ = _data_->_data2_->background;
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp16_ = 0.0F;
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp16_ = clutter_actor_get_width (_data_->_tmp15_);
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp17_ = 0.0F;
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp17_ = _data_->_tmp16_;
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->tex_width = (gint) _data_->_tmp17_;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp18_ = NULL;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp18_ = _data_->_data2_->background;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp19_ = 0.0F;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp19_ = clutter_actor_get_height (_data_->_tmp18_);
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp20_ = 0.0F;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp20_ = _data_->_tmp19_;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->tex_height = (gint) _data_->_tmp20_;
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp21_ = 0;
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp21_ = _data_->reference_x;
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->x_start = _data_->_tmp21_;
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp22_ = 0;
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp22_ = _data_->reference_y;
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->y_start = _data_->_tmp22_;
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp23_ = 0;
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp23_ = _data_->tex_width;
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp24_ = 0;
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp24_ = _data_->reference_x;
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp25_ = 0;
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp25_ = _data_->reference_width;
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp26_ = 0;
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp26_ = MIN (_data_->_tmp23_ - _data_->_tmp24_, _data_->_tmp25_);
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->width = _data_->_tmp26_;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp27_ = 0;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp27_ = _data_->tex_height;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp28_ = 0;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp28_ = _data_->reference_y;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp29_ = 0;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp29_ = _data_->reference_height;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp30_ = 0;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp30_ = MIN (_data_->_tmp27_ - _data_->_tmp28_, _data_->_tmp29_);
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->height = _data_->_tmp30_;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp34_ = 0;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp34_ = _data_->_data2_->x_start;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp35_ = 0;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp35_ = _data_->tex_width;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_data_->_tmp34_ > _data_->_tmp35_) {
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp33_ = TRUE;
#line 1496 "Utils.c"
	} else {
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp36_ = 0;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp36_ = _data_->_data2_->x_start;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp37_ = 0;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp37_ = _data_->tex_height;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp33_ = _data_->_tmp36_ > _data_->_tmp37_;
#line 1508 "Utils.c"
	}
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_data_->_tmp33_) {
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp32_ = TRUE;
#line 1514 "Utils.c"
	} else {
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp38_ = 0;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp38_ = _data_->_data2_->width;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp32_ = _data_->_tmp38_ <= 0;
#line 1522 "Utils.c"
	}
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_data_->_tmp32_) {
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp31_ = TRUE;
#line 1528 "Utils.c"
	} else {
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp39_ = 0;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp39_ = _data_->_data2_->height;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp31_ = _data_->_tmp39_ <= 0;
#line 1536 "Utils.c"
	}
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_data_->_tmp31_) {
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp40_ = 0;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp40_ = _data_->_data2_->x_start;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp41_ = 0;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp41_ = _data_->_data2_->y_start;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp42_ = 0;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp42_ = _data_->_data2_->width;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp43_ = 0;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp43_ = _data_->_data2_->height;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp44_ = NULL;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp44_ = g_strdup_printf ("Invalid rectangle specified: %i, %i, %i, %i", _data_->_tmp40_, _data_->_tmp41_, _data_->_tmp42_, _data_->_tmp43_);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp45_ = NULL;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp45_ = _data_->_tmp44_;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp46_ = NULL;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp46_ = g_error_new_literal (G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, _data_->_tmp45_);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp47_ = NULL;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_tmp47_ = _data_->_tmp46_;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_g_free0 (_data_->_tmp45_);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		_data_->_inner_error_ = _data_->_tmp47_;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		if (_data_->_inner_error_->domain == G_DBUS_ERROR) {
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_simple_async_result_set_from_error (_data_->_async_result, _data_->_inner_error_);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_error_free (_data_->_inner_error_);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			block2_data_unref (_data_->_data2_);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			_data_->_data2_ = NULL;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			if (_data_->_state_ == 0) {
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 1590 "Utils.c"
			} else {
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
				g_simple_async_result_complete (_data_->_async_result);
#line 1594 "Utils.c"
			}
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_object_unref (_data_->_async_result);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			return FALSE;
#line 1600 "Utils.c"
		} else {
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			block2_data_unref (_data_->_data2_);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			_data_->_data2_ = NULL;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			g_clear_error (&_data_->_inner_error_);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
			return FALSE;
#line 1612 "Utils.c"
		}
	}
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->mean_acutance = (gdouble) 0;
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->variance = (gdouble) 0;
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->mean = (gdouble) 0;
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->rTotal = (gdouble) 0;
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->gTotal = (gdouble) 0;
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->bTotal = (gdouble) 0;
#line 71 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->paint_signal_handler = (gulong) 0;
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp48_ = NULL;
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp48_ = _data_->_data2_->effect;
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp49_ = 0UL;
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp49_ = g_signal_connect_data (_data_->_tmp48_, "done-painting", (GCallback) ___lambda8__wingpanel_interface_utils_dummy_offscreen_effect_done_painting, block2_data_ref (_data_->_data2_), (GClosureNotify) block2_data_unref, 0);
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_->paint_signal_handler = _data_->_tmp49_;
#line 192 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp50_ = NULL;
#line 192 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp50_ = _data_->_data2_->background;
#line 192 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	clutter_actor_queue_redraw (_data_->_tmp50_);
#line 194 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_state_ = 1;
#line 194 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	return FALSE;
#line 1649 "Utils.c"
	_state_1:
	;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp51_ = 0.0;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp51_ = _data_->_data2_->rTotal;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp52_ = 0.0;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp52_ = _data_->_data2_->gTotal;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp53_ = 0.0;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp53_ = _data_->_data2_->bTotal;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp54_ = 0.0;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp54_ = _data_->_data2_->mean;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp55_ = 0.0;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp55_ = _data_->_data2_->variance;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp56_ = 0.0;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp56_ = _data_->_data2_->mean_acutance;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	memset (&_data_->_tmp57_, 0, sizeof (WingpanelInterfaceUtilsColorInformation));
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp57_.average_red = _data_->_tmp51_;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp57_.average_green = _data_->_tmp52_;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp57_.average_blue = _data_->_tmp53_;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp57_.mean_luminance = _data_->_tmp54_;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp57_.luminance_variance = _data_->_tmp55_;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_tmp57_.mean_acutance = _data_->_tmp56_;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->result = _data_->_tmp57_;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	block2_data_unref (_data_->_data2_);
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_ = NULL;
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_data_->_state_ == 0) {
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 1700 "Utils.c"
	} else {
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 1704 "Utils.c"
	}
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	g_object_unref (_data_->_async_result);
#line 196 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	return FALSE;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	block2_data_unref (_data_->_data2_);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	_data_->_data2_ = NULL;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	if (_data_->_state_ == 0) {
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 1718 "Utils.c"
	} else {
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 1722 "Utils.c"
	}
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	g_object_unref (_data_->_async_result);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/wingpanel-interface/Utils.vala"
	return FALSE;
#line 1728 "Utils.c"
}



