/* PanelWindow.c generated by valac 0.34.4, the Vala compiler
 * generated from PanelWindow.vala, do not modify */

/*
 * Copyright (c) 2011-2015 Wingpanel Developers (http://launchpad.net/wingpanel)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>
#include <cairo.h>


#define WINGPANEL_TYPE_PANEL_WINDOW (wingpanel_panel_window_get_type ())
#define WINGPANEL_PANEL_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_TYPE_PANEL_WINDOW, WingpanelPanelWindow))
#define WINGPANEL_PANEL_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_TYPE_PANEL_WINDOW, WingpanelPanelWindowClass))
#define WINGPANEL_IS_PANEL_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_TYPE_PANEL_WINDOW))
#define WINGPANEL_IS_PANEL_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_TYPE_PANEL_WINDOW))
#define WINGPANEL_PANEL_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_TYPE_PANEL_WINDOW, WingpanelPanelWindowClass))

typedef struct _WingpanelPanelWindow WingpanelPanelWindow;
typedef struct _WingpanelPanelWindowClass WingpanelPanelWindowClass;
typedef struct _WingpanelPanelWindowPrivate WingpanelPanelWindowPrivate;

#define WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER (wingpanel_services_popover_manager_get_type ())
#define WINGPANEL_SERVICES_POPOVER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER, WingpanelServicesPopoverManager))
#define WINGPANEL_SERVICES_POPOVER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER, WingpanelServicesPopoverManagerClass))
#define WINGPANEL_SERVICES_IS_POPOVER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER))
#define WINGPANEL_SERVICES_IS_POPOVER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER))
#define WINGPANEL_SERVICES_POPOVER_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER, WingpanelServicesPopoverManagerClass))

typedef struct _WingpanelServicesPopoverManager WingpanelServicesPopoverManager;
typedef struct _WingpanelServicesPopoverManagerClass WingpanelServicesPopoverManagerClass;

#define WINGPANEL_WIDGETS_TYPE_PANEL (wingpanel_widgets_panel_get_type ())
#define WINGPANEL_WIDGETS_PANEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanel))
#define WINGPANEL_WIDGETS_PANEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanelClass))
#define WINGPANEL_WIDGETS_IS_PANEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_WIDGETS_TYPE_PANEL))
#define WINGPANEL_WIDGETS_IS_PANEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_WIDGETS_TYPE_PANEL))
#define WINGPANEL_WIDGETS_PANEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanelClass))

typedef struct _WingpanelWidgetsPanel WingpanelWidgetsPanel;
typedef struct _WingpanelWidgetsPanelClass WingpanelWidgetsPanelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER (wingpanel_services_background_manager_get_type ())
#define WINGPANEL_SERVICES_BACKGROUND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER, WingpanelServicesBackgroundManager))
#define WINGPANEL_SERVICES_BACKGROUND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER, WingpanelServicesBackgroundManagerClass))
#define WINGPANEL_SERVICES_IS_BACKGROUND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER))
#define WINGPANEL_SERVICES_IS_BACKGROUND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER))
#define WINGPANEL_SERVICES_BACKGROUND_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER, WingpanelServicesBackgroundManagerClass))

typedef struct _WingpanelServicesBackgroundManager WingpanelServicesBackgroundManager;
typedef struct _WingpanelServicesBackgroundManagerClass WingpanelServicesBackgroundManagerClass;
typedef struct _Block2Data Block2Data;

struct _WingpanelPanelWindow {
	GtkWindow parent_instance;
	WingpanelPanelWindowPrivate * priv;
	WingpanelServicesPopoverManager* popover_manager;
};

struct _WingpanelPanelWindowClass {
	GtkWindowClass parent_class;
};

struct _WingpanelPanelWindowPrivate {
	WingpanelWidgetsPanel* panel;
	gint monitor_number;
	gint monitor_width;
	gint monitor_height;
	gint monitor_x;
	gint monitor_y;
	gint panel_height;
	gboolean expanded;
	gint panel_displacement;
	guint shrink_timeout;
};

struct _Block2Data {
	int _ref_count_;
	WingpanelPanelWindow* self;
	gboolean expanded;
};


static gpointer wingpanel_panel_window_parent_class = NULL;

GType wingpanel_panel_window_get_type (void) G_GNUC_CONST;
GType wingpanel_services_popover_manager_get_type (void) G_GNUC_CONST;
GType wingpanel_widgets_panel_get_type (void) G_GNUC_CONST;
#define WINGPANEL_PANEL_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), WINGPANEL_TYPE_PANEL_WINDOW, WingpanelPanelWindowPrivate))
enum  {
	WINGPANEL_PANEL_WINDOW_DUMMY_PROPERTY
};
WingpanelPanelWindow* wingpanel_panel_window_new (GtkApplication* app);
WingpanelPanelWindow* wingpanel_panel_window_construct (GType object_type, GtkApplication* app);
#define WINGPANEL_WIDGETS_STYLE_CLASS_PANEL "panel"
static void wingpanel_panel_window_update_panel_dimensions (WingpanelPanelWindow* self);
static void _wingpanel_panel_window_update_panel_dimensions_gdk_screen_size_changed (GdkScreen* _sender, gpointer self);
static void _wingpanel_panel_window_update_panel_dimensions_gdk_screen_monitors_changed (GdkScreen* _sender, gpointer self);
static void wingpanel_panel_window_update_visual (WingpanelPanelWindow* self);
static void _wingpanel_panel_window_update_visual_gtk_widget_screen_changed (GtkWidget* _sender, GdkScreen* previous_screen, gpointer self);
WingpanelServicesPopoverManager* wingpanel_services_popover_manager_new (WingpanelPanelWindow* owner);
WingpanelServicesPopoverManager* wingpanel_services_popover_manager_construct (GType object_type, WingpanelPanelWindow* owner);
WingpanelWidgetsPanel* wingpanel_widgets_panel_new (WingpanelServicesPopoverManager* popover_manager);
WingpanelWidgetsPanel* wingpanel_widgets_panel_construct (GType object_type, WingpanelServicesPopoverManager* popover_manager);
static void wingpanel_panel_window_on_realize (WingpanelPanelWindow* self);
static void _wingpanel_panel_window_on_realize_gtk_widget_realize (GtkWidget* _sender, gpointer self);
static void _wingpanel_panel_window_update_panel_dimensions_gtk_widget_size_allocate (GtkWidget* _sender, GtkAllocation* allocation, gpointer self);
void wingpanel_panel_window_set_expanded (WingpanelPanelWindow* self, gboolean expanded);
static gboolean wingpanel_panel_window_animation_step (WingpanelPanelWindow* self);
GType wingpanel_services_background_manager_get_type (void) G_GNUC_CONST;
WingpanelServicesBackgroundManager* wingpanel_services_background_manager_get_default (void);
void wingpanel_services_background_manager_initialize (WingpanelServicesBackgroundManager* self, gint monitor, gint panel_height);
static gboolean _wingpanel_panel_window_animation_step_gsource_func (gpointer self);
GtkPopover* wingpanel_services_popover_manager_get_visible_popover (WingpanelServicesPopoverManager* self);
static void wingpanel_panel_window_update_struts (WingpanelPanelWindow* self);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
void wingpanel_services_background_manager_remember_window (WingpanelServicesBackgroundManager* self);
void wingpanel_services_background_manager_restore_window (WingpanelServicesBackgroundManager* self);
static gboolean ___lambda7_ (Block2Data* _data2_);
static gboolean ____lambda7__gsource_func (gpointer self);
static void wingpanel_panel_window_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 53 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	return self ? g_object_ref (self) : NULL;
#line 150 "PanelWindow.c"
}


static void _wingpanel_panel_window_update_panel_dimensions_gdk_screen_size_changed (GdkScreen* _sender, gpointer self) {
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_update_panel_dimensions ((WingpanelPanelWindow*) self);
#line 157 "PanelWindow.c"
}


static void _wingpanel_panel_window_update_panel_dimensions_gdk_screen_monitors_changed (GdkScreen* _sender, gpointer self) {
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_update_panel_dimensions ((WingpanelPanelWindow*) self);
#line 164 "PanelWindow.c"
}


static void _wingpanel_panel_window_update_visual_gtk_widget_screen_changed (GtkWidget* _sender, GdkScreen* previous_screen, gpointer self) {
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_update_visual ((WingpanelPanelWindow*) self);
#line 171 "PanelWindow.c"
}


static void _wingpanel_panel_window_on_realize_gtk_widget_realize (GtkWidget* _sender, gpointer self) {
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_on_realize ((WingpanelPanelWindow*) self);
#line 178 "PanelWindow.c"
}


static void _wingpanel_panel_window_update_panel_dimensions_gtk_widget_size_allocate (GtkWidget* _sender, GtkAllocation* allocation, gpointer self) {
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_update_panel_dimensions ((WingpanelPanelWindow*) self);
#line 185 "PanelWindow.c"
}


WingpanelPanelWindow* wingpanel_panel_window_construct (GType object_type, GtkApplication* app) {
	WingpanelPanelWindow * self = NULL;
	GdkScreen* _tmp0_ = NULL;
	GdkScreen* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GtkApplication* _tmp3_ = NULL;
	GtkStyleContext* style_context = NULL;
	GtkStyleContext* _tmp4_ = NULL;
	GtkStyleContext* _tmp5_ = NULL;
	GdkScreen* _tmp6_ = NULL;
	GdkScreen* _tmp7_ = NULL;
	GdkScreen* _tmp8_ = NULL;
	GdkScreen* _tmp9_ = NULL;
	WingpanelServicesPopoverManager* _tmp10_ = NULL;
	WingpanelServicesPopoverManager* _tmp11_ = NULL;
	WingpanelWidgetsPanel* _tmp12_ = NULL;
	WingpanelWidgetsPanel* _tmp13_ = NULL;
	WingpanelWidgetsPanel* _tmp14_ = NULL;
	WingpanelWidgetsPanel* _tmp15_ = NULL;
#line 41 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 41 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self = (WingpanelPanelWindow*) g_object_new (object_type, NULL);
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp0_ = gtk_window_get_screen ((GtkWindow*) self);
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp1_ = _tmp0_;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp2_ = gdk_screen_get_primary_monitor (_tmp1_);
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->monitor_number = _tmp2_;
#line 44 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp3_ = app;
#line 44 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_window_set_application ((GtkWindow*) self, _tmp3_);
#line 46 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_window_set_decorated ((GtkWindow*) self, FALSE);
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_window_set_skip_taskbar_hint ((GtkWindow*) self, TRUE);
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_widget_set_app_paintable ((GtkWidget*) self, TRUE);
#line 50 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_window_set_type_hint ((GtkWindow*) self, GDK_WINDOW_TYPE_HINT_DOCK);
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_widget_set_vexpand ((GtkWidget*) self, FALSE);
#line 53 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp4_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 53 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp5_ = _g_object_ref0 (_tmp4_);
#line 53 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	style_context = _tmp5_;
#line 54 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_style_context_add_class (style_context, WINGPANEL_WIDGETS_STYLE_CLASS_PANEL);
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_style_context_add_class (style_context, GTK_STYLE_CLASS_MENUBAR);
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp6_ = gtk_window_get_screen ((GtkWindow*) self);
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp7_ = _tmp6_;
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_signal_connect_object (_tmp7_, "size-changed", (GCallback) _wingpanel_panel_window_update_panel_dimensions_gdk_screen_size_changed, self, 0);
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp8_ = gtk_window_get_screen ((GtkWindow*) self);
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp9_ = _tmp8_;
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_signal_connect_object (_tmp9_, "monitors-changed", (GCallback) _wingpanel_panel_window_update_panel_dimensions_gdk_screen_monitors_changed, self, 0);
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_signal_connect_object ((GtkWidget*) self, "screen-changed", (GCallback) _wingpanel_panel_window_update_visual_gtk_widget_screen_changed, self, 0);
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_update_visual (self);
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp10_ = wingpanel_services_popover_manager_new (self);
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_g_object_unref0 (self->popover_manager);
#line 63 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->popover_manager = _tmp10_;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp11_ = self->popover_manager;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp12_ = wingpanel_widgets_panel_new (_tmp11_);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_object_ref_sink (_tmp12_);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_g_object_unref0 (self->priv->panel);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->panel = _tmp12_;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp13_ = self->priv->panel;
#line 66 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_signal_connect_object ((GtkWidget*) _tmp13_, "realize", (GCallback) _wingpanel_panel_window_on_realize_gtk_widget_realize, self, 0);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp14_ = self->priv->panel;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_signal_connect_object ((GtkWidget*) _tmp14_, "size-allocate", (GCallback) _wingpanel_panel_window_update_panel_dimensions_gtk_widget_size_allocate, self, 0);
#line 69 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp15_ = self->priv->panel;
#line 69 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp15_);
#line 71 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_set_expanded (self, FALSE);
#line 41 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_g_object_unref0 (style_context);
#line 41 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	return self;
#line 296 "PanelWindow.c"
}


WingpanelPanelWindow* wingpanel_panel_window_new (GtkApplication* app) {
#line 41 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	return wingpanel_panel_window_construct (WINGPANEL_TYPE_PANEL_WINDOW, app);
#line 303 "PanelWindow.c"
}


static gboolean wingpanel_panel_window_animation_step (WingpanelPanelWindow* self) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 74 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 75 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp0_ = self->priv->panel_displacement;
#line 75 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp1_ = self->priv->panel_height;
#line 75 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	if (_tmp0_ <= (_tmp1_ * -1)) {
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		result = FALSE;
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		return result;
#line 324 "PanelWindow.c"
	}
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp2_ = self->priv->panel_displacement;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->panel_displacement = _tmp2_ - 1;
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_update_panel_dimensions (self);
#line 83 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	result = TRUE;
#line 83 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	return result;
#line 336 "PanelWindow.c"
}


static gboolean _wingpanel_panel_window_animation_step_gsource_func (gpointer self) {
	gboolean result;
	result = wingpanel_panel_window_animation_step ((WingpanelPanelWindow*) self);
#line 91 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	return result;
#line 345 "PanelWindow.c"
}


static void wingpanel_panel_window_on_realize (WingpanelPanelWindow* self) {
	WingpanelServicesBackgroundManager* _tmp0_ = NULL;
	WingpanelServicesBackgroundManager* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
#line 86 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_return_if_fail (self != NULL);
#line 87 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_update_panel_dimensions (self);
#line 89 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp0_ = wingpanel_services_background_manager_get_default ();
#line 89 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp1_ = _tmp0_;
#line 89 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp2_ = self->priv->monitor_number;
#line 89 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp3_ = self->priv->panel_height;
#line 89 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_services_background_manager_initialize (_tmp1_, _tmp2_, _tmp3_);
#line 89 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_g_object_unref0 (_tmp1_);
#line 91 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp4_ = self->priv->panel_height;
#line 91 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) (300 / _tmp4_), _wingpanel_panel_window_animation_step_gsource_func, g_object_ref (self), g_object_unref);
#line 375 "PanelWindow.c"
}


static void wingpanel_panel_window_update_panel_dimensions (WingpanelPanelWindow* self) {
	WingpanelWidgetsPanel* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GdkScreen* _tmp2_ = NULL;
	GdkScreen* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	GdkRectangle monitor_dimensions = {0};
	GdkScreen* _tmp5_ = NULL;
	GdkScreen* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	GdkRectangle _tmp8_ = {0};
	GdkRectangle _tmp9_ = {0};
	gint _tmp10_ = 0;
	GdkRectangle _tmp11_ = {0};
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
	WingpanelServicesPopoverManager* _tmp14_ = NULL;
	GtkPopover* _tmp15_ = NULL;
	gint _tmp17_ = 0;
	GdkRectangle _tmp18_ = {0};
	gint _tmp19_ = 0;
	GdkRectangle _tmp20_ = {0};
	gint _tmp21_ = 0;
	gint _tmp22_ = 0;
	gint _tmp23_ = 0;
	gint _tmp24_ = 0;
	gint _tmp25_ = 0;
#line 94 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_return_if_fail (self != NULL);
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp0_ = self->priv->panel;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp1_ = gtk_widget_get_allocated_height ((GtkWidget*) _tmp0_);
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->panel_height = _tmp1_;
#line 97 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp2_ = gtk_window_get_screen ((GtkWindow*) self);
#line 97 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp3_ = _tmp2_;
#line 97 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp4_ = gdk_screen_get_primary_monitor (_tmp3_);
#line 97 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->monitor_number = _tmp4_;
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp5_ = gtk_window_get_screen ((GtkWindow*) self);
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp6_ = _tmp5_;
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp7_ = self->priv->monitor_number;
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gdk_screen_get_monitor_geometry (_tmp6_, _tmp7_, &_tmp8_);
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	monitor_dimensions = _tmp8_;
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp9_ = monitor_dimensions;
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp10_ = _tmp9_.width;
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->monitor_width = _tmp10_;
#line 102 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp11_ = monitor_dimensions;
#line 102 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp12_ = _tmp11_.height;
#line 102 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->monitor_height = _tmp12_;
#line 104 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp14_ = self->popover_manager;
#line 104 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp15_ = wingpanel_services_popover_manager_get_visible_popover (_tmp14_);
#line 104 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	if (_tmp15_ != NULL) {
#line 450 "PanelWindow.c"
		gint _tmp16_ = 0;
#line 104 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp16_ = self->priv->monitor_height;
#line 104 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp13_ = _tmp16_;
#line 456 "PanelWindow.c"
	} else {
#line 104 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp13_ = -1;
#line 460 "PanelWindow.c"
	}
#line 104 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp17_ = self->priv->monitor_width;
#line 104 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, _tmp17_, _tmp13_);
#line 106 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp18_ = monitor_dimensions;
#line 106 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp19_ = _tmp18_.x;
#line 106 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->monitor_x = _tmp19_;
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_ = monitor_dimensions;
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp21_ = _tmp20_.y;
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->monitor_y = _tmp21_;
#line 109 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp22_ = self->priv->monitor_x;
#line 109 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp23_ = self->priv->monitor_y;
#line 109 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp24_ = self->priv->panel_height;
#line 109 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp25_ = self->priv->panel_displacement;
#line 109 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_window_move ((GtkWindow*) self, _tmp22_, _tmp23_ - (_tmp24_ + _tmp25_));
#line 111 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_update_struts (self);
#line 490 "PanelWindow.c"
}


static void wingpanel_panel_window_update_visual (WingpanelPanelWindow* self) {
	GdkVisual* visual = NULL;
	GdkScreen* _tmp0_ = NULL;
	GdkScreen* _tmp1_ = NULL;
	GdkVisual* _tmp2_ = NULL;
	GdkVisual* _tmp3_ = NULL;
	GdkVisual* _tmp4_ = NULL;
#line 114 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_return_if_fail (self != NULL);
#line 115 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp0_ = gtk_window_get_screen ((GtkWindow*) self);
#line 115 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp1_ = _tmp0_;
#line 115 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp2_ = gdk_screen_get_rgba_visual (_tmp1_);
#line 115 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 115 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	visual = _tmp3_;
#line 117 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp4_ = visual;
#line 117 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	if (_tmp4_ == NULL) {
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		g_warning ("PanelWindow.vala:118: Compositing not available, things will Look Bad " \
"(TM)");
#line 519 "PanelWindow.c"
	} else {
		GdkVisual* _tmp5_ = NULL;
#line 120 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp5_ = visual;
#line 120 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		gtk_widget_set_visual ((GtkWidget*) self, _tmp5_);
#line 526 "PanelWindow.c"
	}
#line 114 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_g_object_unref0 (visual);
#line 530 "PanelWindow.c"
}


static void wingpanel_panel_window_update_struts (WingpanelPanelWindow* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint monitor = 0;
	gint position_top = 0;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	GdkAtom atom = 0U;
	GdkRectangle primary_monitor_rect = {0};
	glong struts[12] = {0};
	GdkScreen* _tmp11_ = NULL;
	GdkScreen* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	GdkRectangle _tmp14_ = {0};
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
	gint _tmp18_ = 0;
	gint _tmp19_ = 0;
	glong _tmp20_[12] = {0};
	GdkAtom _tmp21_ = 0U;
	GdkWindow* _tmp22_ = NULL;
	GdkAtom _tmp23_ = 0U;
	GdkAtom _tmp24_ = 0U;
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_return_if_fail (self != NULL);
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp1_ = gtk_widget_get_realized ((GtkWidget*) self);
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	if (!_tmp1_) {
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp0_ = TRUE;
#line 568 "PanelWindow.c"
	} else {
		WingpanelWidgetsPanel* _tmp2_ = NULL;
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp2_ = self->priv->panel;
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp0_ = _tmp2_ == NULL;
#line 575 "PanelWindow.c"
	}
#line 125 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	if (_tmp0_) {
#line 126 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		return;
#line 581 "PanelWindow.c"
	}
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp4_ = self->priv->monitor_number;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	if (_tmp4_ == -1) {
#line 587 "PanelWindow.c"
		GdkScreen* _tmp5_ = NULL;
		GdkScreen* _tmp6_ = NULL;
		gint _tmp7_ = 0;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp5_ = gtk_window_get_screen ((GtkWindow*) self);
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp6_ = _tmp5_;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp7_ = gdk_screen_get_primary_monitor (_tmp6_);
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp3_ = _tmp7_;
#line 599 "PanelWindow.c"
	} else {
		gint _tmp8_ = 0;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp8_ = self->priv->monitor_number;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp3_ = _tmp8_;
#line 606 "PanelWindow.c"
	}
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	monitor = _tmp3_;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp9_ = self->priv->monitor_y;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp10_ = self->priv->panel_displacement;
#line 131 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	position_top = _tmp9_ - _tmp10_;
#line 138 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp11_ = gtk_window_get_screen ((GtkWindow*) self);
#line 138 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp12_ = _tmp11_;
#line 138 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp13_ = monitor;
#line 138 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gdk_screen_get_monitor_geometry (_tmp12_, _tmp13_, &_tmp14_);
#line 138 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	primary_monitor_rect = _tmp14_;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp15_ = position_top;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp16_ = gtk_widget_get_scale_factor ((GtkWidget*) self);
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp17_ = self->priv->monitor_x;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp18_ = self->priv->monitor_x;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp19_ = self->priv->monitor_width;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[0] = (glong) 0;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[1] = (glong) 0;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[2] = (glong) (_tmp15_ * _tmp16_);
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[3] = (glong) 0;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[4] = (glong) 0;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[5] = (glong) 0;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[6] = (glong) 0;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[7] = (glong) 0;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[8] = (glong) _tmp17_;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[9] = (glong) ((_tmp18_ + _tmp19_) - 1);
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[10] = (glong) 0;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp20_[11] = (glong) 0;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	memcpy (struts, _tmp20_, 12 * sizeof (glong));
#line 147 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp21_ = gdk_atom_intern ("_NET_WM_STRUT_PARTIAL", FALSE);
#line 147 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	atom = _tmp21_;
#line 149 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp22_ = gtk_widget_get_window ((GtkWidget*) self);
#line 149 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp23_ = atom;
#line 149 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp24_ = gdk_atom_intern ("CARDINAL", FALSE);
#line 149 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gdk_property_change (_tmp22_, _tmp23_, _tmp24_, 32, GDK_PROP_MODE_REPLACE, (const guchar*) ((guint8*) struts), 12);
#line 674 "PanelWindow.c"
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	return _data2_;
#line 683 "PanelWindow.c"
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 692 "PanelWindow.c"
		WingpanelPanelWindow* self;
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		self = _data2_->self;
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_g_object_unref0 (self);
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		g_slice_free (Block2Data, _data2_);
#line 700 "PanelWindow.c"
	}
}


static gboolean ___lambda7_ (Block2Data* _data2_) {
	WingpanelPanelWindow* self;
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	gboolean _tmp1_ = FALSE;
	gint _tmp3_ = 0;
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self = _data2_->self;
#line 175 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->shrink_timeout = (guint) 0;
#line 176 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp1_ = _data2_->expanded;
#line 176 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	if (_tmp1_) {
#line 719 "PanelWindow.c"
		gint _tmp2_ = 0;
#line 176 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp2_ = self->priv->monitor_height;
#line 176 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp0_ = _tmp2_;
#line 725 "PanelWindow.c"
	} else {
#line 176 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp0_ = -1;
#line 729 "PanelWindow.c"
	}
#line 176 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp3_ = self->priv->monitor_width;
#line 176 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, _tmp3_, _tmp0_);
#line 178 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	result = FALSE;
#line 178 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	return result;
#line 739 "PanelWindow.c"
}


static gboolean ____lambda7__gsource_func (gpointer self) {
	gboolean result;
	result = ___lambda7_ (self);
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	return result;
#line 748 "PanelWindow.c"
}


void wingpanel_panel_window_set_expanded (WingpanelPanelWindow* self, gboolean expanded) {
	Block2Data* _data2_;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_return_if_fail (self != NULL);
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_data2_ = g_slice_new0 (Block2Data);
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_data2_->_ref_count_ = 1;
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_data2_->self = g_object_ref (self);
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp0_ = expanded;
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_data2_->expanded = _tmp0_;
#line 154 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_tmp1_ = _data2_->expanded;
#line 154 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	if (_tmp1_) {
#line 772 "PanelWindow.c"
		WingpanelServicesBackgroundManager* _tmp2_ = NULL;
		WingpanelServicesBackgroundManager* _tmp3_ = NULL;
		gboolean _tmp4_ = FALSE;
		guint _tmp5_ = 0U;
		gint _tmp7_ = 0;
		gboolean _tmp8_ = FALSE;
		gint _tmp10_ = 0;
#line 155 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp2_ = wingpanel_services_background_manager_get_default ();
#line 155 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp3_ = _tmp2_;
#line 155 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		wingpanel_services_background_manager_remember_window (_tmp3_);
#line 155 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_g_object_unref0 (_tmp3_);
#line 157 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp4_ = _data2_->expanded;
#line 157 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		self->priv->expanded = _tmp4_;
#line 159 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp5_ = self->priv->shrink_timeout;
#line 159 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		if (_tmp5_ > ((guint) 0)) {
#line 796 "PanelWindow.c"
			guint _tmp6_ = 0U;
#line 160 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
			_tmp6_ = self->priv->shrink_timeout;
#line 160 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
			g_source_remove (_tmp6_);
#line 161 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
			self->priv->shrink_timeout = (guint) 0;
#line 804 "PanelWindow.c"
		}
#line 164 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp8_ = _data2_->expanded;
#line 164 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		if (_tmp8_) {
#line 810 "PanelWindow.c"
			gint _tmp9_ = 0;
#line 164 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
			_tmp9_ = self->priv->monitor_height;
#line 164 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
			_tmp7_ = _tmp9_;
#line 816 "PanelWindow.c"
		} else {
#line 164 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
			_tmp7_ = -1;
#line 820 "PanelWindow.c"
		}
#line 164 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp10_ = self->priv->monitor_width;
#line 164 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		gtk_widget_set_size_request ((GtkWidget*) self, _tmp10_, _tmp7_);
#line 826 "PanelWindow.c"
	} else {
		WingpanelServicesBackgroundManager* _tmp11_ = NULL;
		WingpanelServicesBackgroundManager* _tmp12_ = NULL;
		gboolean _tmp13_ = FALSE;
		guint _tmp14_ = 0U;
		guint _tmp16_ = 0U;
#line 166 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp11_ = wingpanel_services_background_manager_get_default ();
#line 166 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp12_ = _tmp11_;
#line 166 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		wingpanel_services_background_manager_restore_window (_tmp12_);
#line 166 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_g_object_unref0 (_tmp12_);
#line 168 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp13_ = _data2_->expanded;
#line 168 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		self->priv->expanded = _tmp13_;
#line 170 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp14_ = self->priv->shrink_timeout;
#line 170 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		if (_tmp14_ > ((guint) 0)) {
#line 849 "PanelWindow.c"
			guint _tmp15_ = 0U;
#line 171 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
			_tmp15_ = self->priv->shrink_timeout;
#line 171 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
			g_source_remove (_tmp15_);
#line 855 "PanelWindow.c"
		}
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		_tmp16_ = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 300, ____lambda7__gsource_func, block2_data_ref (_data2_), block2_data_unref);
#line 174 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
		self->priv->shrink_timeout = _tmp16_;
#line 861 "PanelWindow.c"
	}
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	block2_data_unref (_data2_);
#line 153 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_data2_ = NULL;
#line 867 "PanelWindow.c"
}


static void wingpanel_panel_window_class_init (WingpanelPanelWindowClass * klass) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	wingpanel_panel_window_parent_class = g_type_class_peek_parent (klass);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	g_type_class_add_private (klass, sizeof (WingpanelPanelWindowPrivate));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	G_OBJECT_CLASS (klass)->finalize = wingpanel_panel_window_finalize;
#line 878 "PanelWindow.c"
}


static void wingpanel_panel_window_instance_init (WingpanelPanelWindow * self) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv = WINGPANEL_PANEL_WINDOW_GET_PRIVATE (self);
#line 39 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self->priv->shrink_timeout = (guint) 0;
#line 887 "PanelWindow.c"
}


static void wingpanel_panel_window_finalize (GObject* obj) {
	WingpanelPanelWindow * self;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WINGPANEL_TYPE_PANEL_WINDOW, WingpanelPanelWindow);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_g_object_unref0 (self->popover_manager);
#line 23 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	_g_object_unref0 (self->priv->panel);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/PanelWindow.vala"
	G_OBJECT_CLASS (wingpanel_panel_window_parent_class)->finalize (obj);
#line 901 "PanelWindow.c"
}


GType wingpanel_panel_window_get_type (void) {
	static volatile gsize wingpanel_panel_window_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_panel_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelPanelWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_panel_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelPanelWindow), 0, (GInstanceInitFunc) wingpanel_panel_window_instance_init, NULL };
		GType wingpanel_panel_window_type_id;
		wingpanel_panel_window_type_id = g_type_register_static (gtk_window_get_type (), "WingpanelPanelWindow", &g_define_type_info, 0);
		g_once_init_leave (&wingpanel_panel_window_type_id__volatile, wingpanel_panel_window_type_id);
	}
	return wingpanel_panel_window_type_id__volatile;
}



