/* IndicatorSorter.c generated by valac 0.34.4, the Vala compiler
 * generated from IndicatorSorter.vala, do not modify */

/*
 * Copyright (c) 2011-2015 Wingpanel Developers (http://launchpad.net/wingpanel)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <wingpanel.h>
#include <gtk/gtk.h>


#define WINGPANEL_SERVICES_TYPE_INDICATOR_SORTER (wingpanel_services_indicator_sorter_get_type ())
#define WINGPANEL_SERVICES_INDICATOR_SORTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_SERVICES_TYPE_INDICATOR_SORTER, WingpanelServicesIndicatorSorter))
#define WINGPANEL_SERVICES_INDICATOR_SORTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_SERVICES_TYPE_INDICATOR_SORTER, WingpanelServicesIndicatorSorterClass))
#define WINGPANEL_SERVICES_IS_INDICATOR_SORTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_SERVICES_TYPE_INDICATOR_SORTER))
#define WINGPANEL_SERVICES_IS_INDICATOR_SORTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_SERVICES_TYPE_INDICATOR_SORTER))
#define WINGPANEL_SERVICES_INDICATOR_SORTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_SERVICES_TYPE_INDICATOR_SORTER, WingpanelServicesIndicatorSorterClass))

typedef struct _WingpanelServicesIndicatorSorter WingpanelServicesIndicatorSorter;
typedef struct _WingpanelServicesIndicatorSorterClass WingpanelServicesIndicatorSorterClass;
typedef struct _WingpanelServicesIndicatorSorterPrivate WingpanelServicesIndicatorSorterPrivate;

#define WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY (wingpanel_widgets_indicator_entry_get_type ())
#define WINGPANEL_WIDGETS_INDICATOR_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY, WingpanelWidgetsIndicatorEntry))
#define WINGPANEL_WIDGETS_INDICATOR_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY, WingpanelWidgetsIndicatorEntryClass))
#define WINGPANEL_WIDGETS_IS_INDICATOR_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY))
#define WINGPANEL_WIDGETS_IS_INDICATOR_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY))
#define WINGPANEL_WIDGETS_INDICATOR_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY, WingpanelWidgetsIndicatorEntryClass))

typedef struct _WingpanelWidgetsIndicatorEntry WingpanelWidgetsIndicatorEntry;
typedef struct _WingpanelWidgetsIndicatorEntryClass WingpanelWidgetsIndicatorEntryClass;
typedef struct _WingpanelWidgetsIndicatorEntryPrivate WingpanelWidgetsIndicatorEntryPrivate;

#define WINGPANEL_WIDGETS_TYPE_MENU_BAR (wingpanel_widgets_menu_bar_get_type ())
#define WINGPANEL_WIDGETS_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_WIDGETS_TYPE_MENU_BAR, WingpanelWidgetsMenuBar))
#define WINGPANEL_WIDGETS_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_WIDGETS_TYPE_MENU_BAR, WingpanelWidgetsMenuBarClass))
#define WINGPANEL_WIDGETS_IS_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_WIDGETS_TYPE_MENU_BAR))
#define WINGPANEL_WIDGETS_IS_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_WIDGETS_TYPE_MENU_BAR))
#define WINGPANEL_WIDGETS_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_WIDGETS_TYPE_MENU_BAR, WingpanelWidgetsMenuBarClass))

typedef struct _WingpanelWidgetsMenuBar WingpanelWidgetsMenuBar;
typedef struct _WingpanelWidgetsMenuBarClass WingpanelWidgetsMenuBarClass;

#define WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR (wingpanel_widgets_indicator_menu_bar_get_type ())
#define WINGPANEL_WIDGETS_INDICATOR_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR, WingpanelWidgetsIndicatorMenuBar))
#define WINGPANEL_WIDGETS_INDICATOR_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR, WingpanelWidgetsIndicatorMenuBarClass))
#define WINGPANEL_WIDGETS_IS_INDICATOR_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR))
#define WINGPANEL_WIDGETS_IS_INDICATOR_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR))
#define WINGPANEL_WIDGETS_INDICATOR_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR, WingpanelWidgetsIndicatorMenuBarClass))

typedef struct _WingpanelWidgetsIndicatorMenuBar WingpanelWidgetsIndicatorMenuBar;
typedef struct _WingpanelWidgetsIndicatorMenuBarClass WingpanelWidgetsIndicatorMenuBarClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _WingpanelServicesIndicatorSorter {
	GObject parent_instance;
	WingpanelServicesIndicatorSorterPrivate * priv;
};

struct _WingpanelServicesIndicatorSorterClass {
	GObjectClass parent_class;
};

struct _WingpanelWidgetsIndicatorEntry {
	GtkMenuItem parent_instance;
	WingpanelWidgetsIndicatorEntryPrivate * priv;
	WingpanelIndicator* base_indicator;
	WingpanelWidgetsIndicatorMenuBar* menu_bar;
};

struct _WingpanelWidgetsIndicatorEntryClass {
	GtkMenuItemClass parent_class;
};


static gpointer wingpanel_services_indicator_sorter_parent_class = NULL;

GType wingpanel_services_indicator_sorter_get_type (void) G_GNUC_CONST;
enum  {
	WINGPANEL_SERVICES_INDICATOR_SORTER_DUMMY_PROPERTY
};
GType wingpanel_widgets_indicator_entry_get_type (void) G_GNUC_CONST;
gint wingpanel_services_indicator_sorter_compare_func (WingpanelServicesIndicatorSorter* self, WingpanelWidgetsIndicatorEntry* a, WingpanelWidgetsIndicatorEntry* b);
static gint wingpanel_services_indicator_sorter_get_order (WingpanelWidgetsIndicatorEntry* node);
static gint wingpanel_services_indicator_sorter_compare_entries_by_name (WingpanelWidgetsIndicatorEntry* a, WingpanelWidgetsIndicatorEntry* b);
GType wingpanel_widgets_menu_bar_get_type (void) G_GNUC_CONST;
GType wingpanel_widgets_indicator_menu_bar_get_type (void) G_GNUC_CONST;
WingpanelServicesIndicatorSorter* wingpanel_services_indicator_sorter_new (void);
WingpanelServicesIndicatorSorter* wingpanel_services_indicator_sorter_construct (GType object_type);

static const gchar* WINGPANEL_SERVICES_INDICATOR_SORTER_INDICATOR_ORDER[10] = {WINGPANEL_INDICATOR_KEYBOARD, WINGPANEL_INDICATOR_SOUND, WINGPANEL_INDICATOR_NETWORK, WINGPANEL_INDICATOR_BLUETOOTH, WINGPANEL_INDICATOR_PRINTER, WINGPANEL_INDICATOR_SYNC, WINGPANEL_INDICATOR_POWER, WINGPANEL_INDICATOR_MESSAGES, WINGPANEL_INDICATOR_SESSION, WINGPANEL_INDICATOR_DATETIME};

gint wingpanel_services_indicator_sorter_compare_func (WingpanelServicesIndicatorSorter* self, WingpanelWidgetsIndicatorEntry* a, WingpanelWidgetsIndicatorEntry* b) {
	gint result = 0;
	WingpanelWidgetsIndicatorEntry* _tmp0_ = NULL;
	WingpanelWidgetsIndicatorEntry* _tmp3_ = NULL;
	gint order = 0;
	WingpanelWidgetsIndicatorEntry* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	WingpanelWidgetsIndicatorEntry* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	gint _tmp12_ = 0;
	gint _tmp13_ = 0;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 43 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp0_ = a;
#line 43 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	if (_tmp0_ == NULL) {
#line 131 "IndicatorSorter.c"
		gint _tmp1_ = 0;
		WingpanelWidgetsIndicatorEntry* _tmp2_ = NULL;
#line 44 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		_tmp2_ = b;
#line 44 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		if (_tmp2_ == NULL) {
#line 44 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
			_tmp1_ = 0;
#line 140 "IndicatorSorter.c"
		} else {
#line 44 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
			_tmp1_ = -1;
#line 144 "IndicatorSorter.c"
		}
#line 44 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		result = _tmp1_;
#line 44 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		return result;
#line 150 "IndicatorSorter.c"
	}
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp3_ = b;
#line 47 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	if (_tmp3_ == NULL) {
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		result = 1;
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		return result;
#line 160 "IndicatorSorter.c"
	}
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp4_ = a;
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp5_ = wingpanel_services_indicator_sorter_get_order (_tmp4_);
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp6_ = b;
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp7_ = wingpanel_services_indicator_sorter_get_order (_tmp6_);
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	order = _tmp5_ - _tmp7_;
#line 53 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp8_ = order;
#line 53 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	if (_tmp8_ == 0) {
#line 176 "IndicatorSorter.c"
		WingpanelWidgetsIndicatorEntry* _tmp9_ = NULL;
		WingpanelWidgetsIndicatorEntry* _tmp10_ = NULL;
		gint _tmp11_ = 0;
#line 54 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		_tmp9_ = a;
#line 54 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		_tmp10_ = b;
#line 54 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		_tmp11_ = wingpanel_services_indicator_sorter_compare_entries_by_name (_tmp9_, _tmp10_);
#line 54 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		order = _tmp11_;
#line 188 "IndicatorSorter.c"
	}
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp12_ = order;
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp13_ = CLAMP (_tmp12_, -1, 1);
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	result = _tmp13_;
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	return result;
#line 198 "IndicatorSorter.c"
}


static gint wingpanel_services_indicator_sorter_compare_entries_by_name (WingpanelWidgetsIndicatorEntry* a, WingpanelWidgetsIndicatorEntry* b) {
	gint result = 0;
	GCompareFunc _tmp0_ = NULL;
	WingpanelWidgetsIndicatorEntry* _tmp1_ = NULL;
	WingpanelIndicator* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	WingpanelWidgetsIndicatorEntry* _tmp7_ = NULL;
	WingpanelIndicator* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gint _tmp13_ = 0;
	gint _tmp14_ = 0;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	g_return_val_if_fail (a != NULL, 0);
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	g_return_val_if_fail (b != NULL, 0);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp0_ = g_strcmp0;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp1_ = a;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp2_ = _tmp1_->base_indicator;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp3_ = wingpanel_indicator_get_code_name (_tmp2_);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp4_ = _tmp3_;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp5_ = g_utf8_strdown (_tmp4_, (gssize) -1);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp6_ = _tmp5_;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp7_ = b;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp8_ = _tmp7_->base_indicator;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp9_ = wingpanel_indicator_get_code_name (_tmp8_);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp10_ = _tmp9_;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp11_ = g_utf8_strdown (_tmp10_, (gssize) -1);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp12_ = _tmp11_;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp13_ = _tmp0_ (_tmp6_, _tmp12_);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp14_ = _tmp13_;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_g_free0 (_tmp12_);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_g_free0 (_tmp6_);
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	result = _tmp14_;
#line 65 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	return result;
#line 261 "IndicatorSorter.c"
}


static gint wingpanel_services_indicator_sorter_get_order (WingpanelWidgetsIndicatorEntry* node) {
	gint result = 0;
	gint best_match = 0;
	WingpanelWidgetsIndicatorEntry* _tmp0_ = NULL;
	WingpanelIndicator* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
#line 68 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	g_return_val_if_fail (node != NULL, 0);
#line 69 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	best_match = 0;
#line 72 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp0_ = node;
#line 72 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp1_ = _tmp0_->base_indicator;
#line 72 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp2_ = wingpanel_indicator_get_code_name (_tmp1_);
#line 72 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp3_ = _tmp2_;
#line 72 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	_tmp4_ = g_str_has_prefix (_tmp3_, "ayatana-");
#line 72 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	if (_tmp4_) {
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		result = best_match;
#line 73 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		return result;
#line 293 "IndicatorSorter.c"
	}
	{
		gint i = 0;
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
		i = 0;
#line 299 "IndicatorSorter.c"
		{
			gboolean _tmp5_ = FALSE;
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
			_tmp5_ = TRUE;
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
			while (TRUE) {
#line 306 "IndicatorSorter.c"
				gint _tmp7_ = 0;
				gchar* order_name = NULL;
				gint _tmp8_ = 0;
				const gchar* _tmp9_ = NULL;
				gchar* _tmp10_ = NULL;
				const gchar* _tmp11_ = NULL;
				WingpanelWidgetsIndicatorEntry* _tmp12_ = NULL;
				WingpanelIndicator* _tmp13_ = NULL;
				const gchar* _tmp14_ = NULL;
				const gchar* _tmp15_ = NULL;
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				if (!_tmp5_) {
#line 319 "IndicatorSorter.c"
					gint _tmp6_ = 0;
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
					_tmp6_ = i;
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
					i = _tmp6_ + 1;
#line 325 "IndicatorSorter.c"
				}
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp5_ = FALSE;
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp7_ = i;
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				if (!(_tmp7_ < G_N_ELEMENTS (WINGPANEL_SERVICES_INDICATOR_SORTER_INDICATOR_ORDER))) {
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
					break;
#line 335 "IndicatorSorter.c"
				}
#line 77 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp8_ = i;
#line 77 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp9_ = WINGPANEL_SERVICES_INDICATOR_SORTER_INDICATOR_ORDER[_tmp8_];
#line 77 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp10_ = g_strdup (_tmp9_);
#line 77 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				order_name = _tmp10_;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp11_ = order_name;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp12_ = node;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp13_ = _tmp12_->base_indicator;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp14_ = wingpanel_indicator_get_code_name (_tmp13_);
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_tmp15_ = _tmp14_;
#line 79 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				if (g_strcmp0 (_tmp11_, _tmp15_) == 0) {
#line 357 "IndicatorSorter.c"
					gint _tmp16_ = 0;
#line 80 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
					_tmp16_ = i;
#line 80 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
					best_match = _tmp16_;
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
					_g_free0 (order_name);
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
					break;
#line 367 "IndicatorSorter.c"
				}
#line 76 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
				_g_free0 (order_name);
#line 371 "IndicatorSorter.c"
			}
		}
	}
#line 85 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	result = best_match;
#line 85 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	return result;
#line 379 "IndicatorSorter.c"
}


WingpanelServicesIndicatorSorter* wingpanel_services_indicator_sorter_construct (GType object_type) {
	WingpanelServicesIndicatorSorter * self = NULL;
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	self = (WingpanelServicesIndicatorSorter*) g_object_new (object_type, NULL);
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	return self;
#line 389 "IndicatorSorter.c"
}


WingpanelServicesIndicatorSorter* wingpanel_services_indicator_sorter_new (void) {
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	return wingpanel_services_indicator_sorter_construct (WINGPANEL_SERVICES_TYPE_INDICATOR_SORTER);
#line 396 "IndicatorSorter.c"
}


static void wingpanel_services_indicator_sorter_class_init (WingpanelServicesIndicatorSorterClass * klass) {
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Services/IndicatorSorter.vala"
	wingpanel_services_indicator_sorter_parent_class = g_type_class_peek_parent (klass);
#line 403 "IndicatorSorter.c"
}


static void wingpanel_services_indicator_sorter_instance_init (WingpanelServicesIndicatorSorter * self) {
}


/**
 * Indicator sorter class.
 *
 * This class is composed of static methods because compare_func() needs
 * to be static in order to work properly, since instance methods cannot
 * be passed as CompareFuncs.
 */
GType wingpanel_services_indicator_sorter_get_type (void) {
	static volatile gsize wingpanel_services_indicator_sorter_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_services_indicator_sorter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelServicesIndicatorSorterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_services_indicator_sorter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelServicesIndicatorSorter), 0, (GInstanceInitFunc) wingpanel_services_indicator_sorter_instance_init, NULL };
		GType wingpanel_services_indicator_sorter_type_id;
		wingpanel_services_indicator_sorter_type_id = g_type_register_static (G_TYPE_OBJECT, "WingpanelServicesIndicatorSorter", &g_define_type_info, 0);
		g_once_init_leave (&wingpanel_services_indicator_sorter_type_id__volatile, wingpanel_services_indicator_sorter_type_id);
	}
	return wingpanel_services_indicator_sorter_type_id__volatile;
}



