# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

src/wingpanel.dir/PanelWindow.c.o: src/PanelWindow.c

src/wingpanel.dir/Services/BackgroundManager.c.o: src/Services/BackgroundManager.c

src/wingpanel.dir/Services/IndicatorSorter.c.o: src/Services/IndicatorSorter.c
src/wingpanel.dir/Services/IndicatorSorter.c.o: lib/wingpanel.h

src/wingpanel.dir/Services/PopoverManager.c.o: src/Services/PopoverManager.c
src/wingpanel.dir/Services/PopoverManager.c.o: lib/wingpanel.h

src/wingpanel.dir/Services/Settings.c.o: src/Services/Settings.c

src/wingpanel.dir/Widgets/IndicatorEntry.c.o: src/Widgets/IndicatorEntry.c
src/wingpanel.dir/Widgets/IndicatorEntry.c.o: lib/wingpanel.h

src/wingpanel.dir/Widgets/IndicatorMenuBar.c.o: src/Widgets/IndicatorMenuBar.c
src/wingpanel.dir/Widgets/IndicatorMenuBar.c.o: lib/wingpanel.h

src/wingpanel.dir/Widgets/IndicatorPopover.c.o: src/Widgets/IndicatorPopover.c

src/wingpanel.dir/Widgets/MenuBar.c.o: src/Widgets/MenuBar.c

src/wingpanel.dir/Widgets/Panel.c.o: src/Widgets/Panel.c
src/wingpanel.dir/Widgets/Panel.c.o: lib/wingpanel.h

src/wingpanel.dir/Widgets/StyleClass.c.o: src/Widgets/StyleClass.c

src/wingpanel.dir/Wingpanel.c.o: src/Wingpanel.c
src/wingpanel.dir/Wingpanel.c.o: lib/wingpanel.h

