/* Panel.c generated by valac 0.34.4, the Vala compiler
 * generated from Panel.vala, do not modify */

/*
 * Copyright (c) 2011-2015 Wingpanel Developers (http://launchpad.net/wingpanel)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <wingpanel.h>
#include <gee.h>


#define WINGPANEL_WIDGETS_TYPE_PANEL (wingpanel_widgets_panel_get_type ())
#define WINGPANEL_WIDGETS_PANEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanel))
#define WINGPANEL_WIDGETS_PANEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanelClass))
#define WINGPANEL_WIDGETS_IS_PANEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_WIDGETS_TYPE_PANEL))
#define WINGPANEL_WIDGETS_IS_PANEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_WIDGETS_TYPE_PANEL))
#define WINGPANEL_WIDGETS_PANEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanelClass))

typedef struct _WingpanelWidgetsPanel WingpanelWidgetsPanel;
typedef struct _WingpanelWidgetsPanelClass WingpanelWidgetsPanelClass;
typedef struct _WingpanelWidgetsPanelPrivate WingpanelWidgetsPanelPrivate;

#define WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER (wingpanel_services_popover_manager_get_type ())
#define WINGPANEL_SERVICES_POPOVER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER, WingpanelServicesPopoverManager))
#define WINGPANEL_SERVICES_POPOVER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER, WingpanelServicesPopoverManagerClass))
#define WINGPANEL_SERVICES_IS_POPOVER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER))
#define WINGPANEL_SERVICES_IS_POPOVER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER))
#define WINGPANEL_SERVICES_POPOVER_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER, WingpanelServicesPopoverManagerClass))

typedef struct _WingpanelServicesPopoverManager WingpanelServicesPopoverManager;
typedef struct _WingpanelServicesPopoverManagerClass WingpanelServicesPopoverManagerClass;

#define WINGPANEL_WIDGETS_TYPE_MENU_BAR (wingpanel_widgets_menu_bar_get_type ())
#define WINGPANEL_WIDGETS_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_WIDGETS_TYPE_MENU_BAR, WingpanelWidgetsMenuBar))
#define WINGPANEL_WIDGETS_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_WIDGETS_TYPE_MENU_BAR, WingpanelWidgetsMenuBarClass))
#define WINGPANEL_WIDGETS_IS_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_WIDGETS_TYPE_MENU_BAR))
#define WINGPANEL_WIDGETS_IS_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_WIDGETS_TYPE_MENU_BAR))
#define WINGPANEL_WIDGETS_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_WIDGETS_TYPE_MENU_BAR, WingpanelWidgetsMenuBarClass))

typedef struct _WingpanelWidgetsMenuBar WingpanelWidgetsMenuBar;
typedef struct _WingpanelWidgetsMenuBarClass WingpanelWidgetsMenuBarClass;

#define WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR (wingpanel_widgets_indicator_menu_bar_get_type ())
#define WINGPANEL_WIDGETS_INDICATOR_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR, WingpanelWidgetsIndicatorMenuBar))
#define WINGPANEL_WIDGETS_INDICATOR_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR, WingpanelWidgetsIndicatorMenuBarClass))
#define WINGPANEL_WIDGETS_IS_INDICATOR_MENU_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR))
#define WINGPANEL_WIDGETS_IS_INDICATOR_MENU_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR))
#define WINGPANEL_WIDGETS_INDICATOR_MENU_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_MENU_BAR, WingpanelWidgetsIndicatorMenuBarClass))

typedef struct _WingpanelWidgetsIndicatorMenuBar WingpanelWidgetsIndicatorMenuBar;
typedef struct _WingpanelWidgetsIndicatorMenuBarClass WingpanelWidgetsIndicatorMenuBarClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER (wingpanel_services_background_manager_get_type ())
#define WINGPANEL_SERVICES_BACKGROUND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER, WingpanelServicesBackgroundManager))
#define WINGPANEL_SERVICES_BACKGROUND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER, WingpanelServicesBackgroundManagerClass))
#define WINGPANEL_SERVICES_IS_BACKGROUND_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER))
#define WINGPANEL_SERVICES_IS_BACKGROUND_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER))
#define WINGPANEL_SERVICES_BACKGROUND_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_SERVICES_TYPE_BACKGROUND_MANAGER, WingpanelServicesBackgroundManagerClass))

typedef struct _WingpanelServicesBackgroundManager WingpanelServicesBackgroundManager;
typedef struct _WingpanelServicesBackgroundManagerClass WingpanelServicesBackgroundManagerClass;

#define WINGPANEL_SERVICES_TYPE_BACKGROUND_STATE (wingpanel_services_background_state_get_type ())

#define WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY (wingpanel_widgets_indicator_entry_get_type ())
#define WINGPANEL_WIDGETS_INDICATOR_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY, WingpanelWidgetsIndicatorEntry))
#define WINGPANEL_WIDGETS_INDICATOR_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY, WingpanelWidgetsIndicatorEntryClass))
#define WINGPANEL_WIDGETS_IS_INDICATOR_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY))
#define WINGPANEL_WIDGETS_IS_INDICATOR_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY))
#define WINGPANEL_WIDGETS_INDICATOR_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY, WingpanelWidgetsIndicatorEntryClass))

typedef struct _WingpanelWidgetsIndicatorEntry WingpanelWidgetsIndicatorEntry;
typedef struct _WingpanelWidgetsIndicatorEntryClass WingpanelWidgetsIndicatorEntryClass;
typedef struct _WingpanelWidgetsIndicatorEntryPrivate WingpanelWidgetsIndicatorEntryPrivate;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _WingpanelWidgetsPanel {
	GtkBox parent_instance;
	WingpanelWidgetsPanelPrivate * priv;
};

struct _WingpanelWidgetsPanelClass {
	GtkBoxClass parent_class;
};

struct _WingpanelWidgetsPanelPrivate {
	WingpanelServicesPopoverManager* _popover_manager;
	WingpanelWidgetsIndicatorMenuBar* right_menubar;
	WingpanelWidgetsMenuBar* left_menubar;
	WingpanelWidgetsMenuBar* center_menubar;
	GtkStyleContext* style_context;
	GtkCssProvider* style_provider;
};

typedef enum  {
	WINGPANEL_SERVICES_BACKGROUND_STATE_LIGHT,
	WINGPANEL_SERVICES_BACKGROUND_STATE_DARK,
	WINGPANEL_SERVICES_BACKGROUND_STATE_MAXIMIZED,
	WINGPANEL_SERVICES_BACKGROUND_STATE_TRANSLUCENT
} WingpanelServicesBackgroundState;

struct _WingpanelWidgetsIndicatorEntry {
	GtkMenuItem parent_instance;
	WingpanelWidgetsIndicatorEntryPrivate * priv;
	WingpanelIndicator* base_indicator;
	WingpanelWidgetsIndicatorMenuBar* menu_bar;
};

struct _WingpanelWidgetsIndicatorEntryClass {
	GtkMenuItemClass parent_class;
};


static gpointer wingpanel_widgets_panel_parent_class = NULL;

GType wingpanel_widgets_panel_get_type (void) G_GNUC_CONST;
GType wingpanel_services_popover_manager_get_type (void) G_GNUC_CONST;
GType wingpanel_widgets_menu_bar_get_type (void) G_GNUC_CONST;
GType wingpanel_widgets_indicator_menu_bar_get_type (void) G_GNUC_CONST;
#define WINGPANEL_WIDGETS_PANEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanelPrivate))
enum  {
	WINGPANEL_WIDGETS_PANEL_DUMMY_PROPERTY,
	WINGPANEL_WIDGETS_PANEL_POPOVER_MANAGER
};
WingpanelWidgetsPanel* wingpanel_widgets_panel_new (WingpanelServicesPopoverManager* popover_manager);
WingpanelWidgetsPanel* wingpanel_widgets_panel_construct (GType object_type, WingpanelServicesPopoverManager* popover_manager);
#define WINGPANEL_WIDGETS_STYLE_CLASS_PANEL "panel"
WingpanelWidgetsMenuBar* wingpanel_widgets_menu_bar_new (void);
WingpanelWidgetsMenuBar* wingpanel_widgets_menu_bar_construct (GType object_type);
WingpanelWidgetsIndicatorMenuBar* wingpanel_widgets_indicator_menu_bar_new (void);
WingpanelWidgetsIndicatorMenuBar* wingpanel_widgets_indicator_menu_bar_construct (GType object_type);
static void wingpanel_widgets_panel_add_indicator (WingpanelWidgetsPanel* self, WingpanelIndicator* indicator);
static void _wingpanel_widgets_panel_add_indicator_wingpanel_indicator_manager_indicator_added (WingpanelIndicatorManager* _sender, WingpanelIndicator* indicator, gpointer self);
static void wingpanel_widgets_panel_remove_indicator (WingpanelWidgetsPanel* self, WingpanelIndicator* indicator);
static void _wingpanel_widgets_panel_remove_indicator_wingpanel_indicator_manager_indicator_removed (WingpanelIndicatorManager* _sender, WingpanelIndicator* indicator, gpointer self);
static gboolean __lambda25_ (WingpanelWidgetsPanel* self, WingpanelIndicator* indicator);
static gboolean ___lambda25__gee_forall_func (gpointer g, gpointer self);
GType wingpanel_services_background_manager_get_type (void) G_GNUC_CONST;
WingpanelServicesBackgroundManager* wingpanel_services_background_manager_get_default (void);
GType wingpanel_services_background_state_get_type (void) G_GNUC_CONST;
static void wingpanel_widgets_panel_update_background (WingpanelWidgetsPanel* self, WingpanelServicesBackgroundState state, guint animation_duration);
static void _wingpanel_widgets_panel_update_background_wingpanel_services_background_manager_background_state_changed (WingpanelServicesBackgroundManager* _sender, WingpanelServicesBackgroundState state, guint animation_duration, gpointer self);
GType wingpanel_widgets_indicator_entry_get_type (void) G_GNUC_CONST;
WingpanelServicesPopoverManager* wingpanel_widgets_panel_get_popover_manager (WingpanelWidgetsPanel* self);
WingpanelWidgetsIndicatorEntry* wingpanel_widgets_indicator_entry_new (WingpanelIndicator* base_indicator, WingpanelServicesPopoverManager* popover_manager);
WingpanelWidgetsIndicatorEntry* wingpanel_widgets_indicator_entry_construct (GType object_type, WingpanelIndicator* base_indicator, WingpanelServicesPopoverManager* popover_manager);
void wingpanel_widgets_indicator_entry_set_transition_type (WingpanelWidgetsIndicatorEntry* self, GtkRevealerTransitionType transition_type);
void wingpanel_widgets_indicator_menu_bar_insert_sorted (WingpanelWidgetsIndicatorMenuBar* self, WingpanelWidgetsIndicatorEntry* item);
static void wingpanel_widgets_panel_remove_indicator_from_container (WingpanelWidgetsPanel* self, GtkContainer* container, WingpanelIndicator* indicator);
static void wingpanel_widgets_panel_set_popover_manager (WingpanelWidgetsPanel* self, WingpanelServicesPopoverManager* value);
static void wingpanel_widgets_panel_finalize (GObject* obj);
static void _vala_wingpanel_widgets_panel_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_wingpanel_widgets_panel_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void _wingpanel_widgets_panel_add_indicator_wingpanel_indicator_manager_indicator_added (WingpanelIndicatorManager* _sender, WingpanelIndicator* indicator, gpointer self) {
#line 53 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	wingpanel_widgets_panel_add_indicator ((WingpanelWidgetsPanel*) self, indicator);
#line 183 "Panel.c"
}


static void _wingpanel_widgets_panel_remove_indicator_wingpanel_indicator_manager_indicator_removed (WingpanelIndicatorManager* _sender, WingpanelIndicator* indicator, gpointer self) {
#line 54 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	wingpanel_widgets_panel_remove_indicator ((WingpanelWidgetsPanel*) self, indicator);
#line 190 "Panel.c"
}


static gboolean __lambda25_ (WingpanelWidgetsPanel* self, WingpanelIndicator* indicator) {
	gboolean result = FALSE;
	WingpanelIndicator* _tmp0_ = NULL;
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_val_if_fail (indicator != NULL, FALSE);
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp0_ = indicator;
#line 57 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	wingpanel_widgets_panel_add_indicator (self, _tmp0_);
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	result = TRUE;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (indicator);
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	return result;
#line 209 "Panel.c"
}


static gboolean ___lambda25__gee_forall_func (gpointer g, gpointer self) {
	gboolean result;
	result = __lambda25_ ((WingpanelWidgetsPanel*) self, (WingpanelIndicator*) g);
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	return result;
#line 218 "Panel.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	return self ? g_object_ref (self) : NULL;
#line 225 "Panel.c"
}


static void _wingpanel_widgets_panel_update_background_wingpanel_services_background_manager_background_state_changed (WingpanelServicesBackgroundManager* _sender, WingpanelServicesBackgroundState state, guint animation_duration, gpointer self) {
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	wingpanel_widgets_panel_update_background ((WingpanelWidgetsPanel*) self, state, animation_duration);
#line 232 "Panel.c"
}


WingpanelWidgetsPanel* wingpanel_widgets_panel_construct (GType object_type, WingpanelServicesPopoverManager* popover_manager) {
	WingpanelWidgetsPanel * self = NULL;
	WingpanelServicesPopoverManager* _tmp0_ = NULL;
	GtkStyleContext* _tmp1_ = NULL;
	WingpanelWidgetsMenuBar* _tmp2_ = NULL;
	WingpanelWidgetsMenuBar* _tmp3_ = NULL;
	WingpanelWidgetsMenuBar* _tmp4_ = NULL;
	WingpanelWidgetsIndicatorMenuBar* _tmp5_ = NULL;
	WingpanelWidgetsIndicatorMenuBar* _tmp6_ = NULL;
	WingpanelWidgetsIndicatorMenuBar* _tmp7_ = NULL;
	WingpanelIndicatorManager* indicator_manager = NULL;
	WingpanelIndicatorManager* _tmp8_ = NULL;
	GeeCollection* _tmp9_ = NULL;
	GeeCollection* _tmp10_ = NULL;
	GtkStyleContext* _tmp11_ = NULL;
	GtkStyleContext* _tmp12_ = NULL;
	WingpanelServicesBackgroundManager* _tmp13_ = NULL;
	WingpanelServicesBackgroundManager* _tmp14_ = NULL;
#line 30 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_val_if_fail (popover_manager != NULL, NULL);
#line 31 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp0_ = popover_manager;
#line 31 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	self = (WingpanelWidgetsPanel*) g_object_new (object_type, "popover-manager", _tmp0_, "orientation", GTK_ORIENTATION_HORIZONTAL, NULL);
#line 33 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, -1, 24);
#line 35 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_widget_set_hexpand ((GtkWidget*) self, TRUE);
#line 36 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_widget_set_vexpand ((GtkWidget*) self, FALSE);
#line 37 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_widget_set_valign ((GtkWidget*) self, GTK_ALIGN_START);
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_style_context_add_class (_tmp1_, WINGPANEL_WIDGETS_STYLE_CLASS_PANEL);
#line 40 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp2_ = wingpanel_widgets_menu_bar_new ();
#line 40 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_object_ref_sink (_tmp2_);
#line 40 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->left_menubar);
#line 40 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	self->priv->left_menubar = _tmp2_;
#line 41 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp3_ = self->priv->left_menubar;
#line 41 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp3_, GTK_ALIGN_START);
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp4_ = self->priv->left_menubar;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp4_, TRUE, TRUE, (guint) 0);
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp5_ = wingpanel_widgets_indicator_menu_bar_new ();
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_object_ref_sink (_tmp5_);
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->right_menubar);
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	self->priv->right_menubar = _tmp5_;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp6_ = self->priv->right_menubar;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_widget_set_halign ((GtkWidget*) _tmp6_, GTK_ALIGN_END);
#line 50 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp7_ = self->priv->right_menubar;
#line 50 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_box_pack_end ((GtkBox*) self, (GtkWidget*) _tmp7_, TRUE, TRUE, (guint) 0);
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp8_ = wingpanel_indicator_manager_get_default ();
#line 52 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	indicator_manager = _tmp8_;
#line 53 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_signal_connect_object (indicator_manager, "indicator-added", (GCallback) _wingpanel_widgets_panel_add_indicator_wingpanel_indicator_manager_indicator_added, self, 0);
#line 54 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_signal_connect_object (indicator_manager, "indicator-removed", (GCallback) _wingpanel_widgets_panel_remove_indicator_wingpanel_indicator_manager_indicator_removed, self, 0);
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp9_ = wingpanel_indicator_manager_get_indicators (indicator_manager);
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp10_ = _tmp9_;
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gee_traversable_foreach ((GeeTraversable*) _tmp10_, ___lambda25__gee_forall_func, self);
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (_tmp10_);
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp11_ = gtk_widget_get_style_context ((GtkWidget*) self);
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp12_ = _g_object_ref0 (_tmp11_);
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->style_context);
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	self->priv->style_context = _tmp12_;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp13_ = wingpanel_services_background_manager_get_default ();
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp14_ = _tmp13_;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_signal_connect_object (_tmp14_, "background-state-changed", (GCallback) _wingpanel_widgets_panel_update_background_wingpanel_services_background_manager_background_state_changed, self, 0);
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (_tmp14_);
#line 30 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	return self;
#line 338 "Panel.c"
}


WingpanelWidgetsPanel* wingpanel_widgets_panel_new (WingpanelServicesPopoverManager* popover_manager) {
#line 30 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	return wingpanel_widgets_panel_construct (WINGPANEL_WIDGETS_TYPE_PANEL, popover_manager);
#line 345 "Panel.c"
}


static void wingpanel_widgets_panel_add_indicator (WingpanelWidgetsPanel* self, WingpanelIndicator* indicator) {
	WingpanelWidgetsIndicatorEntry* indicator_entry = NULL;
	WingpanelIndicator* _tmp0_ = NULL;
	WingpanelServicesPopoverManager* _tmp1_ = NULL;
	WingpanelWidgetsIndicatorEntry* _tmp2_ = NULL;
	WingpanelIndicator* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	GQuark _tmp8_ = 0U;
	WingpanelWidgetsIndicatorEntry* _tmp12_ = NULL;
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_if_fail (self != NULL);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_if_fail (indicator != NULL);
#line 68 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp0_ = indicator;
#line 68 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp1_ = self->priv->_popover_manager;
#line 68 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp2_ = wingpanel_widgets_indicator_entry_new (_tmp0_, _tmp1_);
#line 68 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_object_ref_sink (_tmp2_);
#line 68 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	indicator_entry = _tmp2_;
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp3_ = indicator;
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp4_ = wingpanel_indicator_get_code_name (_tmp3_);
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp5_ = _tmp4_;
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp6_ = _tmp5_;
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp8_ = (NULL == _tmp6_) ? 0 : g_quark_from_string (_tmp6_);
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	if (_tmp8_ == g_quark_from_string (WINGPANEL_INDICATOR_APP_LAUNCHER)) {
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		switch (0) {
#line 388 "Panel.c"
			default:
			{
#line 74 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				break;
#line 393 "Panel.c"
			}
		}
	} else {
#line 70 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		switch (0) {
#line 399 "Panel.c"
			default:
			{
				WingpanelWidgetsIndicatorEntry* _tmp9_ = NULL;
				WingpanelWidgetsIndicatorMenuBar* _tmp10_ = NULL;
				WingpanelWidgetsIndicatorEntry* _tmp11_ = NULL;
#line 80 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				_tmp9_ = indicator_entry;
#line 80 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				wingpanel_widgets_indicator_entry_set_transition_type (_tmp9_, GTK_REVEALER_TRANSITION_TYPE_SLIDE_LEFT);
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				_tmp10_ = self->priv->right_menubar;
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				_tmp11_ = indicator_entry;
#line 81 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				wingpanel_widgets_indicator_menu_bar_insert_sorted (_tmp10_, _tmp11_);
#line 82 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				break;
#line 417 "Panel.c"
			}
		}
	}
#line 85 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp12_ = indicator_entry;
#line 85 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp12_);
#line 67 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (indicator_entry);
#line 427 "Panel.c"
}


static void wingpanel_widgets_panel_remove_indicator (WingpanelWidgetsPanel* self, WingpanelIndicator* indicator) {
	WingpanelWidgetsMenuBar* _tmp0_ = NULL;
	WingpanelIndicator* _tmp1_ = NULL;
	WingpanelWidgetsMenuBar* _tmp2_ = NULL;
	WingpanelIndicator* _tmp3_ = NULL;
	WingpanelWidgetsIndicatorMenuBar* _tmp4_ = NULL;
	WingpanelIndicator* _tmp5_ = NULL;
#line 88 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_if_fail (self != NULL);
#line 88 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_if_fail (indicator != NULL);
#line 89 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp0_ = self->priv->left_menubar;
#line 89 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp1_ = indicator;
#line 89 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	wingpanel_widgets_panel_remove_indicator_from_container (self, (GtkContainer*) _tmp0_, _tmp1_);
#line 90 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp2_ = self->priv->center_menubar;
#line 90 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp3_ = indicator;
#line 90 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	wingpanel_widgets_panel_remove_indicator_from_container (self, (GtkContainer*) _tmp2_, _tmp3_);
#line 91 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp4_ = self->priv->right_menubar;
#line 91 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp5_ = indicator;
#line 91 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	wingpanel_widgets_panel_remove_indicator_from_container (self, (GtkContainer*) _tmp4_, _tmp5_);
#line 460 "Panel.c"
}


static void wingpanel_widgets_panel_remove_indicator_from_container (WingpanelWidgetsPanel* self, GtkContainer* container, WingpanelIndicator* indicator) {
	GtkContainer* _tmp0_ = NULL;
	GList* _tmp1_ = NULL;
#line 94 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_if_fail (self != NULL);
#line 94 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_if_fail (container != NULL);
#line 94 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_if_fail (indicator != NULL);
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp0_ = container;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp1_ = gtk_container_get_children (_tmp0_);
#line 477 "Panel.c"
	{
		GList* child_collection = NULL;
		GList* child_it = NULL;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		child_collection = _tmp1_;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		for (child_it = child_collection; child_it != NULL; child_it = child_it->next) {
#line 485 "Panel.c"
			GtkWidget* child = NULL;
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			child = (GtkWidget*) child_it->data;
#line 489 "Panel.c"
			{
				WingpanelWidgetsIndicatorEntry* entry = NULL;
				GtkWidget* _tmp2_ = NULL;
				gboolean _tmp3_ = FALSE;
				WingpanelWidgetsIndicatorEntry* _tmp4_ = NULL;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				_tmp2_ = child;
#line 96 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				entry = G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, WINGPANEL_WIDGETS_TYPE_INDICATOR_ENTRY) ? ((WingpanelWidgetsIndicatorEntry*) _tmp2_) : NULL;
#line 98 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				_tmp4_ = entry;
#line 98 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				if (_tmp4_ != NULL) {
#line 503 "Panel.c"
					WingpanelWidgetsIndicatorEntry* _tmp5_ = NULL;
					WingpanelIndicator* _tmp6_ = NULL;
					WingpanelIndicator* _tmp7_ = NULL;
#line 98 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					_tmp5_ = entry;
#line 98 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					_tmp6_ = _tmp5_->base_indicator;
#line 98 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					_tmp7_ = indicator;
#line 98 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					_tmp3_ = _tmp6_ == _tmp7_;
#line 515 "Panel.c"
				} else {
#line 98 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					_tmp3_ = FALSE;
#line 519 "Panel.c"
				}
#line 98 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
				if (_tmp3_) {
#line 523 "Panel.c"
					GtkContainer* _tmp8_ = NULL;
					GtkWidget* _tmp9_ = NULL;
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					_tmp8_ = container;
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					_tmp9_ = child;
#line 99 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					gtk_container_remove (_tmp8_, _tmp9_);
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					_g_list_free0 (child_collection);
#line 101 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
					return;
#line 536 "Panel.c"
				}
			}
		}
#line 95 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_g_list_free0 (child_collection);
#line 542 "Panel.c"
	}
}


static void wingpanel_widgets_panel_update_background (WingpanelWidgetsPanel* self, WingpanelServicesBackgroundState state, guint animation_duration) {
	GtkCssProvider* _tmp0_ = NULL;
	gchar* css = NULL;
	guint _tmp4_ = 0U;
	gchar* _tmp5_ = NULL;
	WingpanelServicesBackgroundState _tmp13_ = 0;
	GError * _inner_error_ = NULL;
#line 106 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_if_fail (self != NULL);
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp0_ = self->priv->style_provider;
#line 107 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	if (_tmp0_ == NULL) {
#line 560 "Panel.c"
		GtkCssProvider* _tmp1_ = NULL;
		GtkStyleContext* _tmp2_ = NULL;
		GtkCssProvider* _tmp3_ = NULL;
#line 108 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp1_ = gtk_css_provider_new ();
#line 108 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_g_object_unref0 (self->priv->style_provider);
#line 108 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		self->priv->style_provider = _tmp1_;
#line 109 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp2_ = self->priv->style_context;
#line 109 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp3_ = self->priv->style_provider;
#line 109 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		gtk_style_context_add_provider (_tmp2_, (GtkStyleProvider*) _tmp3_, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
#line 576 "Panel.c"
	}
#line 112 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp4_ = animation_duration;
#line 112 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp5_ = g_strdup_printf ("\n" \
"            .panel {\n" \
"                transition: all %ums ease-in-out;\n" \
"            }\n" \
"        ", _tmp4_);
#line 112 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	css = _tmp5_;
#line 584 "Panel.c"
	{
		GtkCssProvider* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		const gchar* _tmp8_ = NULL;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
#line 119 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp6_ = self->priv->style_provider;
#line 119 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp7_ = css;
#line 119 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp8_ = css;
#line 119 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp9_ = strlen (_tmp8_);
#line 119 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp10_ = _tmp9_;
#line 119 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		gtk_css_provider_load_from_data (_tmp6_, _tmp7_, (gssize) _tmp10_, &_inner_error_);
#line 119 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 605 "Panel.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp11_ = NULL;
		const gchar* _tmp12_ = NULL;
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		e = _inner_error_;
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_inner_error_ = NULL;
#line 121 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp11_ = e;
#line 121 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_tmp12_ = _tmp11_->message;
#line 121 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		g_warning ("Panel.vala:121: Parsing own style configuration failed: %s", _tmp12_);
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_g_error_free0 (e);
#line 627 "Panel.c"
	}
	__finally0:
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		_g_free0 (css);
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		g_clear_error (&_inner_error_);
#line 118 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		return;
#line 640 "Panel.c"
	}
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp13_ = state;
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	switch (_tmp13_) {
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		case WINGPANEL_SERVICES_BACKGROUND_STATE_DARK:
#line 648 "Panel.c"
		{
			GtkStyleContext* _tmp14_ = NULL;
			GtkStyleContext* _tmp15_ = NULL;
			GtkStyleContext* _tmp16_ = NULL;
			GtkStyleContext* _tmp17_ = NULL;
#line 126 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp14_ = self->priv->style_context;
#line 126 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_add_class (_tmp14_, "color-light");
#line 127 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp15_ = self->priv->style_context;
#line 127 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp15_, "color-dark");
#line 128 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp16_ = self->priv->style_context;
#line 128 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp16_, "maximized");
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp17_ = self->priv->style_context;
#line 129 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp17_, "translucent");
#line 130 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			break;
#line 672 "Panel.c"
		}
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		case WINGPANEL_SERVICES_BACKGROUND_STATE_LIGHT:
#line 676 "Panel.c"
		{
			GtkStyleContext* _tmp18_ = NULL;
			GtkStyleContext* _tmp19_ = NULL;
			GtkStyleContext* _tmp20_ = NULL;
			GtkStyleContext* _tmp21_ = NULL;
#line 132 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp18_ = self->priv->style_context;
#line 132 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_add_class (_tmp18_, "color-dark");
#line 133 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp19_ = self->priv->style_context;
#line 133 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp19_, "color-light");
#line 134 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp20_ = self->priv->style_context;
#line 134 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp20_, "maximized");
#line 135 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp21_ = self->priv->style_context;
#line 135 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp21_, "translucent");
#line 136 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			break;
#line 700 "Panel.c"
		}
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		case WINGPANEL_SERVICES_BACKGROUND_STATE_MAXIMIZED:
#line 704 "Panel.c"
		{
			GtkStyleContext* _tmp22_ = NULL;
			GtkStyleContext* _tmp23_ = NULL;
			GtkStyleContext* _tmp24_ = NULL;
			GtkStyleContext* _tmp25_ = NULL;
#line 138 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp22_ = self->priv->style_context;
#line 138 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_add_class (_tmp22_, "maximized");
#line 139 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp23_ = self->priv->style_context;
#line 139 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp23_, "color-light");
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp24_ = self->priv->style_context;
#line 140 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp24_, "color-dark");
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp25_ = self->priv->style_context;
#line 141 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp25_, "translucent");
#line 142 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			break;
#line 728 "Panel.c"
		}
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		case WINGPANEL_SERVICES_BACKGROUND_STATE_TRANSLUCENT:
#line 732 "Panel.c"
		{
			GtkStyleContext* _tmp26_ = NULL;
			GtkStyleContext* _tmp27_ = NULL;
			GtkStyleContext* _tmp28_ = NULL;
			GtkStyleContext* _tmp29_ = NULL;
#line 144 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp26_ = self->priv->style_context;
#line 144 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_add_class (_tmp26_, "translucent");
#line 145 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp27_ = self->priv->style_context;
#line 145 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp27_, "color-light");
#line 146 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp28_ = self->priv->style_context;
#line 146 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp28_, "color-dark");
#line 147 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			_tmp29_ = self->priv->style_context;
#line 147 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			gtk_style_context_remove_class (_tmp29_, "maximized");
#line 148 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
			break;
#line 756 "Panel.c"
		}
		default:
#line 124 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		break;
#line 761 "Panel.c"
	}
#line 106 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_free0 (css);
#line 765 "Panel.c"
}


WingpanelServicesPopoverManager* wingpanel_widgets_panel_get_popover_manager (WingpanelWidgetsPanel* self) {
	WingpanelServicesPopoverManager* result;
	WingpanelServicesPopoverManager* _tmp0_ = NULL;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp0_ = self->priv->_popover_manager;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	result = _tmp0_;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	return result;
#line 780 "Panel.c"
}


static void wingpanel_widgets_panel_set_popover_manager (WingpanelWidgetsPanel* self, WingpanelServicesPopoverManager* value) {
	WingpanelServicesPopoverManager* _tmp0_ = NULL;
	WingpanelServicesPopoverManager* _tmp1_ = NULL;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_return_if_fail (self != NULL);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp0_ = value;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->_popover_manager);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	self->priv->_popover_manager = _tmp1_;
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_object_notify ((GObject *) self, "popover-manager");
#line 799 "Panel.c"
}


static void wingpanel_widgets_panel_class_init (WingpanelWidgetsPanelClass * klass) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	wingpanel_widgets_panel_parent_class = g_type_class_peek_parent (klass);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_type_class_add_private (klass, sizeof (WingpanelWidgetsPanelPrivate));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_wingpanel_widgets_panel_get_property;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_wingpanel_widgets_panel_set_property;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	G_OBJECT_CLASS (klass)->finalize = wingpanel_widgets_panel_finalize;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), WINGPANEL_WIDGETS_PANEL_POPOVER_MANAGER, g_param_spec_object ("popover-manager", "popover-manager", "popover-manager", WINGPANEL_SERVICES_TYPE_POPOVER_MANAGER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 816 "Panel.c"
}


static void wingpanel_widgets_panel_instance_init (WingpanelWidgetsPanel * self) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	self->priv = WINGPANEL_WIDGETS_PANEL_GET_PRIVATE (self);
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	self->priv->style_provider = NULL;
#line 825 "Panel.c"
}


static void wingpanel_widgets_panel_finalize (GObject* obj) {
	WingpanelWidgetsPanel * self;
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanel);
#line 21 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->_popover_manager);
#line 23 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->right_menubar);
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->left_menubar);
#line 25 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->center_menubar);
#line 27 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->style_context);
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	_g_object_unref0 (self->priv->style_provider);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	G_OBJECT_CLASS (wingpanel_widgets_panel_parent_class)->finalize (obj);
#line 847 "Panel.c"
}


GType wingpanel_widgets_panel_get_type (void) {
	static volatile gsize wingpanel_widgets_panel_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_widgets_panel_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelWidgetsPanelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_widgets_panel_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelWidgetsPanel), 0, (GInstanceInitFunc) wingpanel_widgets_panel_instance_init, NULL };
		GType wingpanel_widgets_panel_type_id;
		wingpanel_widgets_panel_type_id = g_type_register_static (gtk_box_get_type (), "WingpanelWidgetsPanel", &g_define_type_info, 0);
		g_once_init_leave (&wingpanel_widgets_panel_type_id__volatile, wingpanel_widgets_panel_type_id);
	}
	return wingpanel_widgets_panel_type_id__volatile;
}


static void _vala_wingpanel_widgets_panel_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	WingpanelWidgetsPanel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanel);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	switch (property_id) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		case WINGPANEL_WIDGETS_PANEL_POPOVER_MANAGER:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		g_value_set_object (value, wingpanel_widgets_panel_get_popover_manager (self));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		break;
#line 874 "Panel.c"
		default:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		break;
#line 880 "Panel.c"
	}
}


static void _vala_wingpanel_widgets_panel_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	WingpanelWidgetsPanel * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, WINGPANEL_WIDGETS_TYPE_PANEL, WingpanelWidgetsPanel);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
	switch (property_id) {
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		case WINGPANEL_WIDGETS_PANEL_POPOVER_MANAGER:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		wingpanel_widgets_panel_set_popover_manager (self, g_value_get_object (value));
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		break;
#line 896 "Panel.c"
		default:
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "/home/carl/Hämtningar/wingpanel-2.0.1/src/Widgets/Panel.vala"
		break;
#line 902 "Panel.c"
	}
}



