/* AutomaticScrollBox.c generated by valac 0.34.4, the Vala compiler
 * generated from AutomaticScrollBox.vala, do not modify */

/*
 * Copyright (c) 2011-2015 Wingpanel Developers (http://launchpad.net/wingpanel)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX (wingpanel_widgets_automatic_scroll_box_get_type ())
#define WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX, WingpanelWidgetsAutomaticScrollBox))
#define WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX, WingpanelWidgetsAutomaticScrollBoxClass))
#define WINGPANEL_WIDGETS_IS_AUTOMATIC_SCROLL_BOX(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX))
#define WINGPANEL_WIDGETS_IS_AUTOMATIC_SCROLL_BOX_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX))
#define WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX, WingpanelWidgetsAutomaticScrollBoxClass))

typedef struct _WingpanelWidgetsAutomaticScrollBox WingpanelWidgetsAutomaticScrollBox;
typedef struct _WingpanelWidgetsAutomaticScrollBoxClass WingpanelWidgetsAutomaticScrollBoxClass;
typedef struct _WingpanelWidgetsAutomaticScrollBoxPrivate WingpanelWidgetsAutomaticScrollBoxPrivate;

struct _WingpanelWidgetsAutomaticScrollBox {
	GtkScrolledWindow parent_instance;
	WingpanelWidgetsAutomaticScrollBoxPrivate * priv;
};

struct _WingpanelWidgetsAutomaticScrollBoxClass {
	GtkScrolledWindowClass parent_class;
};

struct _WingpanelWidgetsAutomaticScrollBoxPrivate {
	gint _max_height;
};


static gpointer wingpanel_widgets_automatic_scroll_box_parent_class = NULL;

GType wingpanel_widgets_automatic_scroll_box_get_type (void) G_GNUC_CONST;
#define WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX, WingpanelWidgetsAutomaticScrollBoxPrivate))
enum  {
	WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX_DUMMY_PROPERTY,
	WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX_MAX_HEIGHT
};
WingpanelWidgetsAutomaticScrollBox* wingpanel_widgets_automatic_scroll_box_new (GtkAdjustment* hadj, GtkAdjustment* vadj);
WingpanelWidgetsAutomaticScrollBox* wingpanel_widgets_automatic_scroll_box_construct (GType object_type, GtkAdjustment* hadj, GtkAdjustment* vadj);
static void wingpanel_widgets_automatic_scroll_box_real_get_preferred_height_for_width (GtkWidget* base, gint width, gint* minimum_height, gint* natural_height);
gint wingpanel_widgets_automatic_scroll_box_get_max_height (WingpanelWidgetsAutomaticScrollBox* self);
static void wingpanel_widgets_automatic_scroll_box_real_get_preferred_height (GtkWidget* base, gint* minimum_height, gint* natural_height);
void wingpanel_widgets_automatic_scroll_box_set_max_height (WingpanelWidgetsAutomaticScrollBox* self, gint value);
static GObject * wingpanel_widgets_automatic_scroll_box_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _gtk_widget_queue_resize_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void wingpanel_widgets_automatic_scroll_box_finalize (GObject* obj);
static void _vala_wingpanel_widgets_automatic_scroll_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_wingpanel_widgets_automatic_scroll_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
     * The adjustments are here to ensure the compatibility with Gtk.ScrolledWindow,
     * but you should probably not use them, as the height of this widget is dynamic.
     */
WingpanelWidgetsAutomaticScrollBox* wingpanel_widgets_automatic_scroll_box_construct (GType object_type, GtkAdjustment* hadj, GtkAdjustment* vadj) {
	WingpanelWidgetsAutomaticScrollBox * self = NULL;
	GtkAdjustment* _tmp0_ = NULL;
	GtkAdjustment* _tmp1_ = NULL;
#line 35 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	_tmp0_ = hadj;
#line 35 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	_tmp1_ = vadj;
#line 35 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	self = (WingpanelWidgetsAutomaticScrollBox*) g_object_new (object_type, "hadjustment", _tmp0_, "vadjustment", _tmp1_, NULL);
#line 34 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	return self;
#line 91 "AutomaticScrollBox.c"
}


WingpanelWidgetsAutomaticScrollBox* wingpanel_widgets_automatic_scroll_box_new (GtkAdjustment* hadj, GtkAdjustment* vadj) {
#line 34 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	return wingpanel_widgets_automatic_scroll_box_construct (WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX, hadj, vadj);
#line 98 "AutomaticScrollBox.c"
}


static void wingpanel_widgets_automatic_scroll_box_real_get_preferred_height_for_width (GtkWidget* base, gint width, gint* minimum_height, gint* natural_height) {
	WingpanelWidgetsAutomaticScrollBox * self;
	gint _vala_minimum_height = 0;
	gint _vala_natural_height = 0;
	GtkWidget* child = NULL;
	GtkWidget* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	self = (WingpanelWidgetsAutomaticScrollBox*) base;
#line 43 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	_tmp0_ = gtk_bin_get_child ((GtkBin*) self);
#line 43 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	child = _tmp0_;
#line 45 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	_tmp1_ = child;
#line 45 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	if (_tmp1_ != NULL) {
#line 119 "AutomaticScrollBox.c"
		GtkWidget* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
		gint _tmp11_ = 0;
#line 46 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp2_ = child;
#line 46 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp3_ = width;
#line 46 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		gtk_widget_get_preferred_height_for_width (_tmp2_, _tmp3_, &_tmp4_, &_tmp5_);
#line 46 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_minimum_height = _tmp4_;
#line 46 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_natural_height = _tmp5_;
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp6_ = self->priv->_max_height;
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp7_ = _vala_minimum_height;
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp8_ = MIN (_tmp6_, _tmp7_);
#line 48 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_minimum_height = _tmp8_;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp9_ = self->priv->_max_height;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp10_ = _vala_natural_height;
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp11_ = MIN (_tmp9_, _tmp10_);
#line 49 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_natural_height = _tmp11_;
#line 156 "AutomaticScrollBox.c"
	} else {
		gint _tmp12_ = 0;
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_natural_height = 0;
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp12_ = _vala_natural_height;
#line 51 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_minimum_height = _tmp12_;
#line 165 "AutomaticScrollBox.c"
	}
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	if (minimum_height) {
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		*minimum_height = _vala_minimum_height;
#line 171 "AutomaticScrollBox.c"
	}
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	if (natural_height) {
#line 42 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		*natural_height = _vala_natural_height;
#line 177 "AutomaticScrollBox.c"
	}
}


static void wingpanel_widgets_automatic_scroll_box_real_get_preferred_height (GtkWidget* base, gint* minimum_height, gint* natural_height) {
	WingpanelWidgetsAutomaticScrollBox * self;
	gint _vala_minimum_height = 0;
	gint _vala_natural_height = 0;
	GtkWidget* child = NULL;
	GtkWidget* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	self = (WingpanelWidgetsAutomaticScrollBox*) base;
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	_tmp0_ = gtk_bin_get_child ((GtkBin*) self);
#line 56 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	child = _tmp0_;
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	_tmp1_ = child;
#line 58 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	if (_tmp1_ != NULL) {
#line 199 "AutomaticScrollBox.c"
		GtkWidget* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		gint _tmp10_ = 0;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp2_ = child;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		gtk_widget_get_preferred_height (_tmp2_, &_tmp3_, &_tmp4_);
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_minimum_height = _tmp3_;
#line 59 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_natural_height = _tmp4_;
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp5_ = self->priv->_max_height;
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp6_ = _vala_minimum_height;
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp7_ = MIN (_tmp5_, _tmp6_);
#line 61 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_minimum_height = _tmp7_;
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp8_ = self->priv->_max_height;
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp9_ = _vala_natural_height;
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp10_ = MIN (_tmp8_, _tmp9_);
#line 62 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_natural_height = _tmp10_;
#line 233 "AutomaticScrollBox.c"
	} else {
		gint _tmp11_ = 0;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_natural_height = 0;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_tmp11_ = _vala_natural_height;
#line 64 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		_vala_minimum_height = _tmp11_;
#line 242 "AutomaticScrollBox.c"
	}
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	if (minimum_height) {
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		*minimum_height = _vala_minimum_height;
#line 248 "AutomaticScrollBox.c"
	}
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	if (natural_height) {
#line 55 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		*natural_height = _vala_natural_height;
#line 254 "AutomaticScrollBox.c"
	}
}


gint wingpanel_widgets_automatic_scroll_box_get_max_height (WingpanelWidgetsAutomaticScrollBox* self) {
	gint result;
	gint _tmp0_ = 0;
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	_tmp0_ = self->priv->_max_height;
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	result = _tmp0_;
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	return result;
#line 270 "AutomaticScrollBox.c"
}


void wingpanel_widgets_automatic_scroll_box_set_max_height (WingpanelWidgetsAutomaticScrollBox* self, gint value) {
	gint _tmp0_ = 0;
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	g_return_if_fail (self != NULL);
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	_tmp0_ = value;
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	self->priv->_max_height = _tmp0_;
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	g_object_notify ((GObject *) self, "max-height");
#line 284 "AutomaticScrollBox.c"
}


static void _gtk_widget_queue_resize_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 39 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	gtk_widget_queue_resize ((GtkWidget*) self);
#line 291 "AutomaticScrollBox.c"
}


static GObject * wingpanel_widgets_automatic_scroll_box_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	WingpanelWidgetsAutomaticScrollBox * self;
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	parent_class = G_OBJECT_CLASS (wingpanel_widgets_automatic_scroll_box_parent_class);
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX, WingpanelWidgetsAutomaticScrollBox);
#line 39 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	g_signal_connect_object ((GObject*) self, "notify::max-height", (GCallback) _gtk_widget_queue_resize_g_object_notify, (GtkWidget*) self, 0);
#line 38 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	return obj;
#line 309 "AutomaticScrollBox.c"
}


static void wingpanel_widgets_automatic_scroll_box_class_init (WingpanelWidgetsAutomaticScrollBoxClass * klass) {
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	wingpanel_widgets_automatic_scroll_box_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	g_type_class_add_private (klass, sizeof (WingpanelWidgetsAutomaticScrollBoxPrivate));
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	((GtkWidgetClass *) klass)->get_preferred_height_for_width = wingpanel_widgets_automatic_scroll_box_real_get_preferred_height_for_width;
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	((GtkWidgetClass *) klass)->get_preferred_height = wingpanel_widgets_automatic_scroll_box_real_get_preferred_height;
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_wingpanel_widgets_automatic_scroll_box_get_property;
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_wingpanel_widgets_automatic_scroll_box_set_property;
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	G_OBJECT_CLASS (klass)->constructor = wingpanel_widgets_automatic_scroll_box_constructor;
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	G_OBJECT_CLASS (klass)->finalize = wingpanel_widgets_automatic_scroll_box_finalize;
#line 330 "AutomaticScrollBox.c"
	/**
	     * The maximal height of the scroll box before it starts scrolling.
	     */
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX_MAX_HEIGHT, g_param_spec_int ("max-height", "max-height", "max-height", G_MININT, G_MAXINT, 512, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 336 "AutomaticScrollBox.c"
}


static void wingpanel_widgets_automatic_scroll_box_instance_init (WingpanelWidgetsAutomaticScrollBox * self) {
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	self->priv = WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX_GET_PRIVATE (self);
#line 28 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	self->priv->_max_height = 512;
#line 345 "AutomaticScrollBox.c"
}


static void wingpanel_widgets_automatic_scroll_box_finalize (GObject* obj) {
	WingpanelWidgetsAutomaticScrollBox * self;
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX, WingpanelWidgetsAutomaticScrollBox);
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	G_OBJECT_CLASS (wingpanel_widgets_automatic_scroll_box_parent_class)->finalize (obj);
#line 355 "AutomaticScrollBox.c"
}


/**
 * A scroll box that takes its child's height, unless that height is more than max_height.
 * If it is actually higher than max_height, then it will stick to max_height.
 */
GType wingpanel_widgets_automatic_scroll_box_get_type (void) {
	static volatile gsize wingpanel_widgets_automatic_scroll_box_type_id__volatile = 0;
	if (g_once_init_enter (&wingpanel_widgets_automatic_scroll_box_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WingpanelWidgetsAutomaticScrollBoxClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) wingpanel_widgets_automatic_scroll_box_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WingpanelWidgetsAutomaticScrollBox), 0, (GInstanceInitFunc) wingpanel_widgets_automatic_scroll_box_instance_init, NULL };
		GType wingpanel_widgets_automatic_scroll_box_type_id;
		wingpanel_widgets_automatic_scroll_box_type_id = g_type_register_static (gtk_scrolled_window_get_type (), "WingpanelWidgetsAutomaticScrollBox", &g_define_type_info, 0);
		g_once_init_leave (&wingpanel_widgets_automatic_scroll_box_type_id__volatile, wingpanel_widgets_automatic_scroll_box_type_id);
	}
	return wingpanel_widgets_automatic_scroll_box_type_id__volatile;
}


static void _vala_wingpanel_widgets_automatic_scroll_box_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	WingpanelWidgetsAutomaticScrollBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX, WingpanelWidgetsAutomaticScrollBox);
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	switch (property_id) {
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		case WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX_MAX_HEIGHT:
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		g_value_set_int (value, wingpanel_widgets_automatic_scroll_box_get_max_height (self));
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		break;
#line 386 "AutomaticScrollBox.c"
		default:
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		break;
#line 392 "AutomaticScrollBox.c"
	}
}


static void _vala_wingpanel_widgets_automatic_scroll_box_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	WingpanelWidgetsAutomaticScrollBox * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, WINGPANEL_WIDGETS_TYPE_AUTOMATIC_SCROLL_BOX, WingpanelWidgetsAutomaticScrollBox);
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
	switch (property_id) {
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		case WINGPANEL_WIDGETS_AUTOMATIC_SCROLL_BOX_MAX_HEIGHT:
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		wingpanel_widgets_automatic_scroll_box_set_max_height (self, g_value_get_int (value));
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		break;
#line 408 "AutomaticScrollBox.c"
		default:
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 24 "/home/carl/Hämtningar/wingpanel-2.0.1/lib/Widgets/AutomaticScrollBox.vala"
		break;
#line 414 "AutomaticScrollBox.c"
	}
}



